#!/usr/bin/env node
// Generate corpus.toml from the reference checkout (CONTRACT section 7.7). The hand-written parts (owners, families, the
// bench rows) live in this file; the sha256 of every source file at the pin is read from the checkout, so a pin bump
// regenerates the manifest and `contract corpus --check` shows what changed.
import { createHash } from "node:crypto"
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { fileURLToPath } from "node:url"
import { piSource } from "../lib/run.mjs"

const pi = piSource()
const sha = rel => createHash("sha256").update(readFileSync(join(pi, rel))).digest("hex")
const q = s => JSON.stringify(s)

// Owner lanes (the production-core lanes of docs/plan/durable-core). session: Session kernel, record encoding, documents,
// tasks, scheduler, inbox, sub-agents. loop: generation, tools, prompt and context derivation, output, usage. store: records,
// the store, compaction, edits, forks, reset. host: hosts, the JS facade, bundles.
const E = {
	"00-conversation": ["session", "a Session stores conversations, entries, tasks, documents"],
	"01-documents": ["session", "documents next to transcript entries"],
	"02-forks": ["store", "fork a conversation"],
	"03-owned-conversations": ["session", "a background task that owns a child conversation"],
	"04-chord-state": ["session", "a document exposed through Chord"],
	"05-watches": ["session", "serialize asynchronous document work with a watch"],
	"06-harness": ["loop", "open a Harness with a registry of extensions"],
	"07-configuration": ["loop", "per-conversation agent choices and Harness settings"],
	"08-harness-conversations": ["session", "conversation handles, typed entries, created conversations, forks"],
	"09-context": ["store", "transcript history and model context"],
	"10-registry-reload": ["loop", "reload extension code through the registry"],
	"11-extension-state": ["loop", "an extension's per-conversation document"],
	"12-tasks": ["session", "run a durable task"],
	"13-recovery": ["session", "close, reopen, continue where a task stopped"],
	"14-chat": ["loop", "a chat turn"],
	"15-system-prompt": ["loop", "system prompt sections and instructions"],
	"16-real-model": ["loop", "a real model (OpenAI); no key, no cassette: skipped"],
	"17-coding-tools": ["loop", "a coding-agent tool turn"],
	"18-print": ["loop", "print mode, faux path"],
	"19-json": ["loop", "JSON mode, faux path"],
	"20-inbox": ["session", "the inbox while a conversation is busy"],
	"21-late-join": ["session", "a client attaches mid-run"],
	"22-subagent-foreground": ["session", "a foreground subagent tool"],
	"23-subagent-background": ["session", "persistent background subagents"],
	"24-child-tasks": ["session", "a task that owns child tasks"],
	"25-compaction": ["store", "compaction of a long chat"],
	"26-coding-agent": ["loop", "a small coding agent"],
	"27-plan-mode": ["loop", "plan mode"],
	"28-reviewer": ["loop", "a reviewer agent"],
	"29-sandbox-per-conversation": ["loop", "one sandbox per conversation"],
	"30-tool-override": ["loop", "replace and decorate a tool"],
	"31-reload-and-restart": ["session", "reload an extension while a call runs, then restart"],
}
const U = {
	"chord-guide": "session", "env-line-scan": "host", "env-node-conformance": "host", "env-node-spill": "host", "env-node": "host", "env-truncate": "host",
	"harness-compaction": "store", "harness-context": "store", "harness-conversations": "session", "harness-events": "session", "harness-generation-recovery": "loop",
	"harness-generation": "loop", "harness-inbox": "session", "harness-inspect": "session", "harness-lifecycle": "session", "harness-live-deltas": "loop",
	"harness-output-skip": "loop", "harness-output": "loop", "harness-ownership": "session", "harness-prompt": "loop", "harness-registry": "loop",
	"harness-structured": "session", "harness-submissions": "session", "harness-task-graph": "session", "harness-tasks-recovery": "session", "harness-tasks": "session",
	"harness-tools-recovery": "loop", "harness-tools": "loop", "harness-view": "session", "jsonl-storage": "host", "memory-storage": "host",
	"provider-session-cache-e2e": "loop", "session-checkpoints-migrations": "session", "session-definitions": "session", "session-documents": "session",
	"session-forks": "store", "session-states": "session", "session-tables": "store", "session-watches": "session", "spec-usage": "store",
	"sqlite-cloudflare": "host", "sqlite-facade": "host", "sqlite-migrations": "store", "sqlite-storage": "store", "storage-runtime-boundary": "store",
	"system-order-cache-e2e": "loop", "tools-read-differential": "loop", "tools": "loop", "types": "store",
}
const out = []
const emit = (...lines) => out.push(...lines, "")
emit(
	"# The scenario manifest (CONTRACT section 7.7). Generated by tools/gen-corpus.mjs from the reference checkout; the hashes pin each",
	"# source at the reference commit. `contract corpus --check` fails when a source drifted. Owners are the production-core lanes",
	"# (store, session, loop, host); a failing row is reported against its owner.",
	"#",
	"# levels: store (every Pi table byte for byte), commit (each commit's row changes), context (the pi-ai Context of every model",
	"# call), output (what the scenario prints). normalisers are empty: determinism comes from detenv, not from rewriting values.",
	"# status: ready (a runner exists and the reference capture is deterministic), skipped (cannot run here, with the reason).",
	"",
	"[pin]", `reference = ${q("earendil-works/pi")}`, `commit = ${q("da866ada17bc78c81855d091ab06ab8fb3b6e16e")}`, `release = ${q("1.0.4")}`,
)
for (const f of readdirSync(join(pi, "packages/durable/test/examples")).filter(f => /^\d\d-.*\.ts$/.test(f)).sort()) {
	const name = f.replace(/\.ts$/, "")
	const [owner, about] = E[name]
	const skip = name === "16-real-model"
	emit("[[scenario]]", `id = ${q("E" + name.slice(0, 2))}`, `family = "example"`, `runner = "example"`, `source = ${q("packages/durable/test/examples/" + f)}`,
		`sha256 = ${q(sha("packages/durable/test/examples/" + f))}`, `owner = ${q("dcore-" + owner)}`, `about = ${q(about)}`,
		`levels = ["store", "commit", "context", "output"]`, `normalisers = []`, ...(skip ? [`status = "skipped"`, `reason = "needs OPENAI_API_KEY; a recorded cassette is owner-supplied (CONTRACT section 6)"`] : [`status = "ready"`]))
}
for (const f of readdirSync(join(pi, "packages/durable/test")).filter(f => f.endsWith(".test.ts")).sort()) {
	const name = f.replace(/\.test\.ts$/, "")
	emit("[[scenario]]", `id = ${q("U-" + name)}`, `family = "upstream-test"`, `runner = "vitest"`, `source = ${q("packages/durable/test/" + f)}`, `sha256 = ${q(sha("packages/durable/test/" + f))}`,
		`owner = ${q("dcore-" + U[name])}`, `levels = ["tests"]`, `status = "ready"`)
}
emit("[[scenario]]", `id = "SC"`, `family = "storage-conformance"`, `runner = "storage-conformance"`, `source = "packages/durable/src/testing/storage-conformance.ts"`, `sha256 = ${q(sha("packages/durable/src/testing/storage-conformance.ts"))}`,
	`owner = "dcore-store"`, `about = "the core's write encoder wrapped as a Storage passes the upstream storage conformance suite (CONTRACT 3.10)"`, `levels = ["tests"]`, `status = "ready"`)
emit("[[scenario]]", `id = "I"`, `family = "interop"`, `runner = "interop"`, `source = "durable/interop/scenario.mjs"`, `owner = "dcore-host"`,
	`about = "documents, a task-starting tool, a fork with init, compaction and a reset, then the Go port reads the store"`, `levels = ["store", "commit", "output"]`, `status = "ready"`)
// The bench rows: params go to scenarios/bench.mjs. sizes are turns of history in the fixture.
const bench = (id, family, owner, about, params, extra = [], status = "ready") => emit("[[scenario]]", `id = ${q(id)}`, `family = ${q(family)}`, `runner = "bench"`, `owner = ${q("dcore-" + owner)}`, `about = ${q(about)}`, `levels = ["store", "commit", "context"]`, `params = ${params}`, ...extra, `status = ${q(status)}`)
for (const n of [50, 250, 1000, 3500]) bench(`W1-${n}`, "bench", "loop", `durable-bench, full-walk scripted model, ten 8-tool measured turns after ${n} turns of history, open/close per sample`, `{ fixture = "pi-main-${n}", turns = 10, tools = 8, variant = "full" }`)
for (const n of [50, 250, 1000, 3500]) bench(`W2-${n}`, "bench", "loop", `as W1 with the incremental scripted model; must produce W1's fingerprints`, `{ fixture = "pi-main-${n}", turns = 10, tools = 8, variant = "incr" }`)
for (const [n, ms] of [[50, 100], [50, 250], [1000, 100]]) bench(`W3-${n}-${ms}`, "streaming", "loop", `streaming: 40-60 chunk responses over 1-2 s virtual time, partialIntervalMs ${ms}, crash at every partial commit`, `{ fixture = "pi-main-${n}", turns = 2, tools = 2, variant = "full", stream = 2000, partialMs = ${ms} }`)
for (const n of [1000, 3500]) bench(`W4a-${n}`, "bench", "store", `compaction-bounded history of ${n} turns (fixture written with compaction on and a 200k-token window; measured turns run with compaction disabled)`, `{ fixture = "compact-${n}", turns = 10, tools = 8, variant = "full" }`, [`status_note = "fixture: cli/fixtures.mjs --compact (compaction on, 200k window, 8 KiB tool results)"`])
for (const n of [50, 1000, 3500]) bench(`W4b-${n}`, "bench", "store", `every turn cold: the runtime restarts between measured turns`, `{ fixture = "pi-main-${n}", turns = ${n === 3500 ? 3 : 10}, tools = 8, variant = "full", restartEachTurn = true }`)
for (const n of [50, 1000]) bench(`W4c-${n}`, "bench", "loop", `20-50 KB bounded tool outputs`, `{ fixture = "pi-main-${n}", turns = 4, tools = 4, variant = "full", payloadKb = 32 }`)
bench("W4d", "bench", "loop", "a parallel round of 3 tools", `{ fixture = "pi-main-50", turns = 4, tools = 3, variant = "full", parallel = true }`)
bench("W4e", "bench", "session", "a foreground sub-agent (the tool of example 22): a child conversation the tool call owns, on a history of 50 turns", `{ fixture = "pi-main-50", turns = 2, tools = 1, variant = "full", subagent = true }`)
emit("[[scenario]]", `id = "W4f"`, `family = "wire"`, `runner = "cassette"`, `owner = "dcore-loop"`, `about = "recorded OpenAI Responses and Anthropic Messages streams (wire plane, ADR D11)"`, `levels = ["store", "commit", "context"]`, `status = "skipped"`, `reason = "needs provider cassettes recorded with an owner key (RISKS-AND-QUESTIONS Q6)"`)
bench("W4g", "bench", "loop", "a retryable provider error, then success", `{ fixture = "pi-main-50", turns = 2, tools = 1, variant = "full", fault = "retryable-error" }`)
bench("X1", "mutation", "store", "W1 at 50 with unknown fields injected into one entry and the pi.usage and pi.live document bases before the measured turns (CONTRACT 2.3)", `{ fixture = "pi-main-50", turns = 10, tools = 8, variant = "full", inject = ["entry", "usage", "live"] }`)
emit("[[scenario]]", `id = "X1-live"`, `family = "mutation"`, `runner = "matrix"`, `owner = "dcore-session"`, `about = "W1 at 50 crashed at 12 points; unknown fields injected into the live tasks (record, state, checkpoint, input) and submission before recovery"`,
	`scenario = "W1-50"`, `crash_points = "12"`, `orders = ["P>X", "X>P", "X>X"]`, `inject_at_crash = ["task", "state", "checkpoint", "input", "submission"]`, `levels = ["store", "commit"]`, `status = "ready"`)
for (const [id, n, ks] of [["H-50", 50, "all"], ["H-1000", 1000, "all"], ["H-3500", 3500, "10"], ["H-W3", 50, "all"], ["H-W4d", 50, "all"]]) {
	emit("[[scenario]]", `id = ${q(id)}`, `family = "handoff"`, `runner = "matrix"`, `owner = "dcore-loop"`, `about = ${q(id === "H-W3" ? "crash at every partial commit of W3" : id === "H-W4d" ? "crash at every commit of the parallel round" : `crash after every commit of one measured turn at ${n} turns (${ks} crash points), P>X, X>P, X>X`)}`,
		`scenario = ${q(id === "H-W3" ? "W3-50-100" : id === "H-W4d" ? "W4d" : "W1-" + n)}`, `crash_points = ${q(ks)}`, `orders = ["P>X", "X>P", "X>X"]`, `levels = ["store", "commit", "context"]`, `status = "ready"`)
}
// R: a store written by Pi 1.0.4 (PIN `release`) stays readable. Main and the candidate each extend it with measured turns and
// recover it from crashes; the 1.0.4 record shapes lack main's task startedAt/endedAt and message durationMs, which a reader
// must treat as absent and a writer must not add to rows it does not rewrite.
bench("R-104-50", "legacy", "session", "W1 at 50 turns on a store written by Pi 1.0.4: the reference main and the candidate read it and extend it identically", `{ fixture = "v1.0.4-50", turns = 3, tools = 8, variant = "full" }`)
emit("[[scenario]]", `id = "H-R-104"`, `family = "legacy"`, `runner = "matrix"`, `owner = "dcore-session"`, `about = "crash after every commit of one measured turn on a 1.0.4 store (all crash points), P>X, X>P, X>X"`,
	`scenario = "W1-50"`, `fixture = "v1.0.4-50"`, `crash_points = "all"`, `orders = ["P>X", "X>P", "X>X"]`, `levels = ["store", "commit", "context"]`, `status = "ready"`)
writeFileSync(fileURLToPath(new URL("../corpus.toml", import.meta.url)), out.join("\n"))
console.log(`corpus.toml: ${out.filter(l => l === "[[scenario]]").length} scenarios`)
