#!/usr/bin/env node
// Oracle vectors for the byte-level differential tests (CONTRACT section 5.6), generated by running the reference's own code:
//   encode.jsonl  {in, out}      JSON text in, JSON.stringify(JSON.parse(in)) out (key order, number format, escapes)
//   scan.jsonl    {record, index} an entry record and what a JSON.parse-based extraction reads from it
//   chord.jsonl   {before, after, ops}   diffRevisions(before, after) of @earendil-works/chord at the pin
//   args.jsonl    {tool, call, ok|error} pi-ai validateToolArguments(tool, call): converted arguments or the error text
//   uuid.jsonl    {calls, out}   a sequence of uuidv7() calls in one process with scripted clock and random bytes
// Run under the hooks (it imports the reference's modules):
//   CONTRACT_PI_SOURCE=... CONTRACT_TRACE=/dev/null node --conditions=source --experimental-strip-types --import hooks/register.mjs tools/gen-oracle.mjs <outdir>
import { mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { pathToFileURL } from "node:url"
import { diffRevisions } from "@earendil-works/chord/delta"
import { Type } from "@earendil-works/pi-ai"
import { validateToolArguments } from "@earendil-works/pi-ai/utils/validation"

const outDir = process.argv[2]
if (!outDir) { console.error("usage: gen-oracle.mjs <outdir>"); process.exit(2) }
mkdirSync(outDir, { recursive: true })

let s = 0x9e3779b9
const rnd = () => { s = (s + 0x6d2b79f5) >>> 0; let t = s; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296 }
const int = n => Math.floor(rnd() * n)
const pick = a => a[int(a.length)]
const write = (name, rows) => writeFileSync(join(outDir, name), rows.map(r => JSON.stringify(r)).join("\n") + "\n")

// ---- encode: the text the core reads and the bytes pi-durable would store.
const ESC = ['"', "\\", "\n", "\t", "\u0000", "\u001f", "\u2028", "\u2029", "é", "漢", "😀", "\ud800", "\udfff", "/", "\u007f"]
const rawString = () => Array.from({ length: int(12) }, () => (rnd() < 0.5 ? String.fromCharCode(97 + int(26)) : pick(ESC))).join("")
// A JSON string literal as text, with lone surrogates and control characters as \u escapes JSON.parse accepts.
const lit = str => JSON.stringify(str).replace(/[\ud800-\udfff]/g, (c, i, all) => c) // JSON.stringify already escapes lone surrogates
const NUMS = ["0", "-0", "0.0", "1", "-1", "1e0", "1E3", "1.5e300", "1e21", "1e-7", "1.7976931348623157e308", "5e-324", "123456789012345678901234567890", "0.1", "0.30000000000000004", "100", "1e100", "0.000001", "0.0000001", "4.35", "9007199254740993", "-1e-7", "12345678901234567890", "1.0", "2.50"]
function valueText(depth = 0) {
	const r = rnd()
	if (depth > 3 || r < 0.3) return pick(NUMS)
	if (r < 0.5) return lit(rawString())
	if (r < 0.6) return pick(["true", "false", "null"])
	if (r < 0.75) return `[${Array.from({ length: int(4) }, () => valueText(depth + 1)).join(pick([",", " , ", "\n,"]))}]`
	const keys = Array.from({ length: int(5) }, () => pick(["a", "b", "z", "10", "2", "1", "02", "-1", "1.5", "kind", "id", lit_(rawString()), "__proto__", "constructor", "4294967294", "4294967295", "x\\u0079"]))
	return `{${keys.map(k => `${k.startsWith('"') ? k : JSON.stringify(k.replace(/\\u0079/, "y")).replace('"xy"', '"x\\u0079"')}:${pick(["", " "])}${valueText(depth + 1)}`).join(",")}}`
}
const lit_ = str => lit(str)
const encodeRows = []
for (const t of ['{"b":1,"2":2,"1":3}', '{"a":1,"a":2}', '{"__proto__":1}', '"\\ud800"', '"\\ud83d\\ude00"', '"\\u2028\\u2029"', '[-0,0,-0.0]', '{"10":1,"9":2,"a":3,"01":4}', '[1e21,1e-7,123456789012345678901234567890]', '{"x\\u0079":1}', '"\\/"', '"\\u007f\\u0000\\u001f"', '{"4294967295":1,"4294967294":2}']) encodeRows.push({ in: t })
while (encodeRows.length < 400) encodeRows.push({ in: valueText() })
// Number::toString switches layout at 1e-7 and 1e21 and keeps the shortest round-trip digits: one row on each side of every switch. After the random rows, so the generator's stream for the other families is unchanged.
for (const n of ["1e20", "1e21", "999999999999999900000", "123456789012345680000", "1.5e20", "1.5e21", "1e-6", "1.5e-6", "1e-7", "1.2345e-7", "123e-20", "0.000001234", "5e-324", "2.2250738585072014e-308", "1e999", "-1e999", "1e23", "9007199254740991", "9007199254740992", "0.00001", "1e5", "1.0e1", "-0.0", "0.5e1", "1.7976931348623157e308", "4.35", "100000000000000000000", "0.1e-5", "1E+2"]) encodeRows.push({ in: `[${n}]` }, { in: n })
for (const row of encodeRows) row.out = JSON.stringify(JSON.parse(row.in))
write("encode.jsonl", encodeRows)

// ---- scan: entry records in the shapes pi-durable writes, with adversarial variation.
const text = () => lit(rawString() + pick(["", '"role":"user"', '{\\"kind\\":\\"x\\"}', "\\\\", ""]))
function entryRecord() {
	const kind = pick(["pi.user", "pi.assistant", "pi.tool-result", "pi.system", "pi.compaction", "app.custom"])
	const msg = kind === "pi.user" ? `{"role":"user","content":${pick([text(), `[{"type":"text","text":${text()}},{"type":"image","data":"${"QUJD".repeat(int(50))}","mimeType":"image/png"}]`])},"timestamp":${int(1e12)}}`
		: kind === "pi.assistant" ? `{"role":"assistant","content":[{"type":"toolCall","id":"c1","name":"lookup","arguments":{"role":"user","kind":"pi.user","n":${int(100)},"s":${text()}}},{"type":"text","text":${text()}}],"api":"faux","provider":"faux","model":"m","usage":{"input":1,"output":2},"stopReason":"${pick(["stop", "toolUse", "error", "aborted", "length"])}","timestamp":${int(1e12)}${pick(["", ',"durationMs":5'])}}`
		: kind === "pi.tool-result" ? `{"role":"toolResult","toolCallId":"c1","toolName":"lookup","content":[{"type":"text","text":${text()}}],"isError":false,"timestamp":1}`
		: kind === "pi.system" ? `{"role":"system","content":${text()},"timestamp":1}` : null
	const id = 1 + int(1e6), conversationId = 1 + int(5)
	const head = kind === "pi.compaction" ? id - int(id) : undefined
	const parts = []
	if (msg) parts.push(`"model":[${msg}]`)
	parts.push(`"kind":${JSON.stringify(kind).replace("pi.", rnd() < 0.15 ? "pi\\u002e" : "pi.")}`, `"id":${id}`, `"conversationId":${conversationId}`)
	if (head !== undefined) parts.push(`"head":${head}`)
	if (rnd() < 0.3) parts.push(`"byTaskId":${int(1000)}`)
	if (rnd() < 0.3) parts.splice(int(parts.length + 1), 0, `"zz":{"role":"user","kind":"pi.user","model":[{"role":"assistant"}]}`)
	// pi-durable writes a fixed key order; a store written by anything else may not.
	if (rnd() < 0.4) for (let i = parts.length - 1; i > 0; i--) { const j = int(i + 1); [parts[i], parts[j]] = [parts[j], parts[i]] }
	return `{${parts.join(rnd() < 0.2 ? " , " : ",")}}`
}
const scanRows = []
while (scanRows.length < 300) {
	const record = entryRecord()
	const o = JSON.parse(record)
	const m = o.model?.[0]
	scanRows.push({ record, index: { kind: o.kind, id: o.id, conversationId: o.conversationId, head: o.head ?? null, role: m?.role ?? null, stopReason: m?.stopReason ?? null, messages: o.model?.length ?? 0 } })
}
write("scan.jsonl", scanRows)

// ---- chord: document edit sequences.
const words = () => Array.from({ length: int(8) }, () => pick(["alpha", "beta", "gamma", "δ", "x".repeat(int(20)), "😀"])).join(" ")
function doc() { return { title: words(), items: Array.from({ length: int(4) }, () => ({ id: int(10), text: words(), tags: Array.from({ length: int(3) }, words) })), n: int(100), flag: rnd() < 0.5, nested: { a: words(), b: [int(5), int(5)] } } }
const chordRows = []
const mutate = v => {
	const c = structuredClone(v)
	const r = int(8)
	if (r === 0) c.title += words()
	else if (r === 1) c.title = c.title.slice(int(c.title.length + 1))
	else if (r === 2) c.items.push({ id: int(10), text: words(), tags: [] })
	else if (r === 3) c.items.splice(int(c.items.length + 1), 1)
	else if (r === 4) c.n = int(100)
	else if (r === 5) c.nested.a = c.nested.a.slice(0, int(c.nested.a.length + 1)) + words()
	else if (r === 6) c.nested.b.reverse()
	else c.items.reverse()
	return c
}
while (chordRows.length < 200) { const before = doc(), after = rnd() < 0.2 ? doc() : mutate(before); chordRows.push({ before, after, ops: diffRevisions(before, after) }) }
// Long strings (the 64 KiB overlap search) and trim/append detection.
for (const n of [100, 1000, 65536, 70000]) {
	const base = Array.from({ length: n }, (_, i) => String.fromCharCode(97 + (i * 7) % 26)).join("")
	const afters = n < 65536 ? [base + "tail", "head" + base, base.slice(5), base.slice(0, -5), base.slice(0, n >> 1) + "MID" + base.slice(n >> 1)] : ["head" + base, base.slice(0, n >> 1) + "MID" + base.slice(n >> 1)]
	for (const after of afters) chordRows.push({ before: { s: base }, after: { s: after }, ops: diffRevisions({ s: base }, { s: after }) })
}
write("chord.jsonl", chordRows)

// ---- args: validateToolArguments with a TypeBox schema and with a plain JSON schema.
const tools = {
	lookup: { name: "lookup", description: "d", parameters: Type.Object({ n: Type.Number() }) },
	edit: { name: "edit", description: "d", parameters: Type.Object({ path: Type.String(), count: Type.Optional(Type.Integer()), flag: Type.Optional(Type.Boolean()), tags: Type.Optional(Type.Array(Type.String())) }) },
	plain: { name: "plain", description: "d", parameters: { type: "object", properties: { b: { type: "number" }, a: { type: "string" }, ok: { type: "boolean" }, list: { type: "array", items: { type: "integer" } } }, required: ["a"] } },
}
const goodValue = p => (p.type === "number" || p.type === "integer" ? int(1000) : p.type === "boolean" ? rnd() < 0.5 : p.type === "array" ? Array.from({ length: int(3) }, () => (p.items?.type === "integer" ? int(9) : "t")) : "text" + int(9))
const argRows = []
const argValues = () => pick([1, "1", "1.5", "abc", true, "true", "false", 0, "0", null, [], [1, "2"], ["a"], {}, 3.7, "007", 1e21, "1e3", -0])
for (const [name, tool] of Object.entries(tools)) {
	const keys = Object.keys(tool.parameters.properties)
	for (let i = 0; i < 60; i++) {
		const args = {}
		for (const k of [...keys].sort(() => rnd() - 0.5)) if (rnd() < 0.85) args[k] = rnd() < 0.55 ? goodValue(tool.parameters.properties[k]) : argValues()
		if (rnd() < 0.2) args.extra = argValues()
		const row = { tool: { name, description: "d", parameters: JSON.parse(JSON.stringify(tool.parameters)) }, plainSchema: !Object.getOwnPropertySymbols(tool.parameters).length, call: { type: "toolCall", id: "c", name, arguments: args } }
		try { row.ok = JSON.stringify(validateToolArguments(tool, row.call)) } catch (e) { row.error = e.message }
		argRows.push(row)
	}
}
write("args.jsonl", argRows)

// ---- uuid: calls in one process with a scripted clock and random bytes; a fresh module instance per sequence.
const uuidRows = []
const real = pathToFileURL(`${process.env.CONTRACT_PI_SOURCE}/packages/ai/src/utils/uuid.ts`).href
for (let seq = 0; seq < 30; seq++) {
	const { uuidv7 } = await import(`${real}?real&seq=${seq}`)
	const calls = [], out = []
	let now = 1_700_000_000_000 + int(1e9)
	for (let i = 0; i < 1 + int(12); i++) {
		const ts = rnd() < 0.2 ? 1_600_000_000_000 + int(1e9) : undefined
		now += pick([0, 0, 1, int(5000), -int(3000)])
		const bytes = Array.from({ length: 16 }, () => int(256))
		calls.push({ now, ...(ts === undefined ? {} : { ts }), random: bytes.map(b => b.toString(16).padStart(2, "0")).join("") })
		const realNow = Date.now, realGrv = crypto.getRandomValues
		Date.now = () => now
		Object.defineProperty(globalThis.crypto, "getRandomValues", { value: a => { a.set(bytes); return a }, configurable: true, writable: true })
		try { out.push(uuidv7(ts)) } finally { Date.now = realNow; Object.defineProperty(globalThis.crypto, "getRandomValues", { value: realGrv, configurable: true, writable: true }) }
	}
	uuidRows.push({ calls, out })
}
write("uuid.jsonl", uuidRows)
console.log(`oracle vectors written to ${outDir}: encode ${encodeRows.length}, scan ${scanRows.length}, chord ${chordRows.length}, args ${argRows.length} (${argRows.filter(r => r.error).length} errors), uuid ${uuidRows.length}`)
