package nodepath

import (
	"encoding/json"
	"errors"
	"os"
	"runtime"
	"strings"
	"testing"

	"github.com/MichaelKinsy/PiG/internal/testenv"
)

// resolveCase is one output of Node 24's path.win32.resolve or path.posix.resolve,
// generated by testdata/generate.mjs with process.cwd and the "=C:" drive
// variables replaced by Cwd and Env.
type resolveCase struct {
	Flavor string            `json:"flavor"`
	Cwd    string            `json:"cwd"`
	Env    map[string]string `json:"env"`
	Args   []string          `json:"args"`
	Want   string            `json:"want"`
	// CwdThrows makes process.cwd() throw; Throws is the code Node's resolve then throws.
	CwdThrows bool   `json:"cwdThrows"`
	Throws    string `json:"throws"`
}

type absoluteCase struct {
	Flavor string `json:"flavor"`
	Input  string `json:"input"`
	Want   bool   `json:"want"`
}

type namespacedCase struct {
	Cwd   string `json:"cwd"`
	Input string `json:"input"`
	Want  string `json:"want"`
}

type caseFile struct {
	Namespaced []namespacedCase `json:"namespaced"`
	Resolve    []resolveCase    `json:"resolve"`
	IsAbsolute []absoluteCase   `json:"isAbsolute"`
}

func loadCaseFile(t *testing.T) caseFile {
	t.Helper()
	data, err := os.ReadFile("testdata/resolve_cases.json")
	if err != nil {
		t.Fatal(err)
	}
	var cases caseFile
	if err := json.Unmarshal(data, &cases); err != nil {
		t.Fatal(err)
	}
	return cases
}

func loadCases(t *testing.T) []resolveCase {
	t.Helper()
	return loadCaseFile(t).Resolve
}

func TestToNamespacedPathMatchesNode(t *testing.T) {
	cases := loadCaseFile(t).Namespaced
	if len(cases) < 20 {
		t.Fatalf("case table is too small: %d", len(cases))
	}
	for _, c := range cases {
		got, err := Win32ToNamespacedPath(Env{Cwd: c.Cwd}, c.Input)
		if err != nil || got != c.Want {
			t.Errorf("toNamespacedPath(%q) with cwd %q = %q, %v; Node gives %q", c.Input, c.Cwd, got, err, c.Want)
		}
	}
	if runtime.GOOS != "windows" {
		if got, err := ToNamespacedPath("x"); err != nil || got != "x" {
			t.Errorf("posix toNamespacedPath is the identity, got %q, %v", got, err)
		}
	}
}

func TestIsAbsoluteMatchesNode(t *testing.T) {
	cases := loadCaseFile(t).IsAbsolute
	if len(cases) < 40 {
		t.Fatalf("case table is too small: %d", len(cases))
	}
	for _, c := range cases {
		var got bool
		switch c.Flavor {
		case "win32":
			got = Win32IsAbsolute(c.Input)
		case "posix":
			got = PosixIsAbsolute(c.Input)
		default:
			t.Fatalf("unknown flavor %q", c.Flavor)
		}
		if got != c.Want {
			t.Errorf("%s isAbsolute(%q) = %v, Node gives %v", c.Flavor, c.Input, got, c.Want)
		}
	}
}

var errCwd = errors.New("ENOENT: process.cwd failed")

func (c resolveCase) env() Env {
	var cwdErr error
	if c.CwdThrows {
		cwdErr = errCwd
	}
	return Env{Cwd: c.Cwd, CwdErr: cwdErr, DriveCwd: func(device string) string { return c.Env["="+device] }}
}

// TestResolveMatchesNode runs on every OS: both flavors take their process state as input.
func TestResolveMatchesNode(t *testing.T) {
	seen := map[string]int{}
	throws := 0
	for _, c := range loadCases(t) {
		seen[c.Flavor]++
		if c.Throws != "" {
			throws++
		}
		name := c.Flavor + " cwd=" + c.Cwd + " " + strings.Join(c.Args, "|")
		t.Run(name, func(t *testing.T) {
			var got string
			var err error
			switch c.Flavor {
			case "win32":
				got, err = Win32Resolve(c.env(), c.Args...)
			case "posix":
				got, err = PosixResolve(c.env(), c.Args...)
			default:
				t.Fatalf("unknown flavor %q", c.Flavor)
			}
			if c.Throws != "" {
				if !errors.Is(err, errCwd) {
					t.Errorf("resolve(%q) = %q, %v; Node throws %s from process.cwd()", c.Args, got, err, c.Throws)
				}
				return
			}
			if err != nil {
				t.Fatalf("resolve(%q) with cwd %q env %v failed: %v; Node gives %q", c.Args, c.Cwd, c.Env, err, c.Want)
			}
			if got != c.Want {
				t.Errorf("resolve(%q) with cwd %q env %v = %q, Node gives %q", c.Args, c.Cwd, c.Env, got, c.Want)
			}
		})
	}
	if seen["win32"] < 50 || seen["posix"] < 10 || throws < 10 {
		t.Fatalf("case table is too small: %v, %d throwing", seen, throws)
	}
}

// TestWin32ResolveBugs pins the two Windows divergences from filepath.
func TestWin32ResolveBugs(t *testing.T) {
	env := Env{Cwd: `C:\work`}
	if got, err := Win32Resolve(env, `\x`); err != nil || got != `C:\x` {
		t.Errorf("rooted path must use the process drive, got %q, %v", got, err)
	}
	if got, err := Win32Resolve(env, `\tools\x.`); err != nil || got != `C:\tools\x.` {
		t.Errorf("trailing dot must survive, got %q, %v", got, err)
	}
}

func TestResolveUsesHostFlavor(t *testing.T) {
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	got, err := Resolve("a", "..", "b.")
	if err != nil {
		t.Fatal(err)
	}
	if runtime.GOOS == "windows" {
		if want, _ := Win32Resolve(Process(), "a", "..", "b."); got != want {
			t.Errorf("Resolve = %q, want %q", got, want)
		}
		return
	}
	if want, _ := PosixResolve(Env{Cwd: cwd}, "a", "..", "b."); got != want || !strings.HasSuffix(got, "/b.") {
		t.Errorf("Resolve = %q, want %q", got, want)
	}
}

// TestResolveDeletedWorkingDirectory drives the host Resolve with a real
// unreadable working directory: Node's path.resolve throws ENOENT from
// process.cwd() for a relative path and never reads it for an absolute one.
func TestResolveDeletedWorkingDirectory(t *testing.T) {
	testenv.DeletedWorkingDirectory(t)
	for _, args := range [][]string{{"session.jsonl"}, {"a", "b"}, {"."}, {""}, {}} {
		if got, err := Resolve(args...); !errors.Is(err, os.ErrNotExist) {
			t.Errorf("Resolve(%q) = %q, %v; Node throws ENOENT", args, got, err)
		}
	}
	if got, err := Resolve("x", "/abs/./y"); err != nil || got != "/abs/y" {
		t.Errorf("Resolve with an absolute argument = %q, %v; Node never reads the cwd", got, err)
	}
}
