// SPDX-FileCopyrightText: Copyright Hewlett Packard Enterprise Development LP
// SPDX-License-Identifier: MIT

//go:build ignore

// Command genwidth extracts grok-mermaid's WIDTHS table (from width-data.ts,
// generated from the unicode-width crate) into Go, so the mermaid port measures
// display width identically to pi's bundled grok-mermaid@0.2.2. Re-run after an
// upstream bump:
//
//	node -e '...'  # (path resolved from coding/upstream.go, see below)
//	go run ./internal/mermaid/genwidth <path-to-grok-mermaid/src/width-data.ts>
package main

import (
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
)

const outPath = "internal/mermaid/width_data.go"

var runRE = regexp.MustCompile(`\[\s*(0x[0-9a-fA-F]+),\s*(0x[0-9a-fA-F]+),\s*(\d+)\s*\]`)

func main() {
	if len(os.Args) < 2 {
		fail(fmt.Errorf("usage: genwidth <width-data.ts>"))
	}
	src, err := os.ReadFile(os.Args[1])
	if err != nil {
		fail(err)
	}
	matches := runRE.FindAllStringSubmatch(string(src), -1)
	if len(matches) == 0 {
		fail(fmt.Errorf("no WIDTHS runs parsed"))
	}

	var b strings.Builder
	// REUSE-IgnoreStart
	b.WriteString("// SPDX-FileCopyrightText: Copyright Hewlett Packard Enterprise Development LP\n")
	b.WriteString("// SPDX-FileCopyrightText: Copyright 2023-2026 SpaceXAI\n")
	b.WriteString("// SPDX-FileCopyrightText: Copyright 2026 Alexey Zaytsev\n")
	b.WriteString("// SPDX-FileCopyrightText: Copyright (c) 2015 The Rust Project Developers\n")
	b.WriteString("// SPDX-License-Identifier: Apache-2.0 AND MIT\n\n")
	// REUSE-IgnoreEnd
	b.WriteString("// Code generated by internal/mermaid/genwidth; DO NOT EDIT.\n")
	b.WriteString("// Source: grok-mermaid src/width-data.ts (unicode-width crate), the width\n")
	b.WriteString("// table pi's bundled grok-mermaid uses. Sorted [lo, hi, width] runs.\n\n")
	b.WriteString("package mermaid\n\n")
	b.WriteString("var widthRuns = [][3]int32{\n")
	for _, m := range matches {
		lo, _ := strconv.ParseInt(m[1][2:], 16, 64)
		hi, _ := strconv.ParseInt(m[2][2:], 16, 64)
		w, _ := strconv.Atoi(m[3])
		fmt.Fprintf(&b, "\t{0x%x, 0x%x, %d},\n", lo, hi, w)
	}
	b.WriteString("}\n")

	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s (%d width runs)\n", outPath, len(matches))
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "genwidth:", err)
	os.Exit(1)
}
