#!/bin/sh
# SPDX-FileCopyrightText: Copyright Hewlett Packard Enterprise Development LP
# SPDX-License-Identifier: MIT
# Compare generated bytes without hiding a missing or unreadable artifact.
set -eu
if [ "$#" -ne 3 ]; then
    echo "usage: check-generated.sh <generated> <committed> <make-target>" >&2
    exit 2
fi
if cmp -s "$1" "$2"; then
    exit 0
fi
printf '%s: generated file is missing, unreadable, or stale\n' "$2" >&2
printf 'run: make generate (or: make %s), then commit the result\n' "$3" >&2
exit 1
