package delta

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"
)

// Array roots (tracker.ts track([...]), tracker.test.ts "emits deletion and supports root arrays"). The goldens in testdata/pi_array_root_operations.json are the batches and values the pinned tracker.ts records for 800 seeded edit scripts over an array root (regenerated by pi_array_root_operations.mjs).

// Pi source: packages/chord/src/delta/tracker.ts
// mutation-checked: zeroing the results of Tracker.Revision fails it
func TestTrackerSupportsRootArrays(t *testing.T) {
	object := Track(JsonObjectOf("keep", 1.0, "remove", 2.0))
	change := object.BeginChange()
	change.State().Delete("remove")
	prepared := mustPrepare(t, change)
	if err := object.Adopt(prepared); err != nil {
		t.Fatal(err)
	}
	if textOf(t, object.Value()) != `{"keep":1}` {
		t.Fatalf("object %v", object.Value())
	}

	tracker := TrackArray([]any{1.0, 2.0, 3.0})
	change = tracker.BeginChange()
	elements := change.Elements()
	elements.Reverse()
	if _, err := elements.Push(4.0); err != nil {
		t.Fatal(err)
	}
	prepared = mustPrepare(t, change)
	if got := jsonTextOf(t, prepared.Ops()); got != `[["m",[],[2,1,0]],["p",[],3,0,[4]]]` {
		t.Fatalf("ops %s", got)
	}
	if err := tracker.Adopt(prepared); err != nil {
		t.Fatal(err)
	}
	if got := jsonTextOf(t, tracker.Root()); got != `[3,2,1,4]` {
		t.Fatalf("value %s", got)
	}
	if tracker.Value() != nil {
		t.Fatal("Value is the object root accessor and is nil for an array root")
	}
	if tracker.Revision() != 1 {
		t.Fatalf("revision %d", tracker.Revision())
	}
}

func TestTrackerRootKindsAndReplacement(t *testing.T) {
	tracker := TrackArray([]any{1.0})
	// An object draft of an array root does not exist, and an array draft of an object root does not either.
	if state := tracker.BeginChange().State(); state != nil {
		t.Fatal("an array root has no object draft")
	}
	if elements := Track(NewJsonObject(0)).BeginChange().Elements(); elements != nil {
		t.Fatal("an object root has no array draft")
	}
	// tracker.ts prepareReplace takes any object root and records one root replacement, also across kinds; an equal value records nothing.
	for _, step := range []struct {
		value any
		ops   string
	}{
		{[]any{1.0, JsonObjectOf("b", 2.0)}, `[["r",[1,{"b":2}]]]`},
		{JsonObjectOf("a", 1.0), `[["r",{"a":1}]]`},
		{JsonObjectOf("a", 1.0), `[]`},
		{[]any{}, `[["r",[]]]`},
	} {
		prepared, err := tracker.PrepareReplaceRoot(step.value)
		if err != nil {
			t.Fatal(err)
		}
		if got := jsonTextOf(t, prepared.Ops()); got != step.ops {
			t.Fatalf("ops %s, want %s", got, step.ops)
		}
		if err := tracker.Adopt(prepared); err != nil {
			t.Fatal(err)
		}
		if got, want := jsonTextOf(t, tracker.Root()), jsonTextOf(t, step.value); got != want {
			t.Fatalf("root %s, want %s", got, want)
		}
	}
	if _, err := tracker.PrepareReplaceRoot("text"); err == nil {
		t.Fatal("a primitive is not a root")
	}
	// A preparation made before another adoption is stale, as for object roots.
	stale := TrackArray([]any{1.0})
	first, second := stale.BeginChange(), stale.BeginChange()
	_, _ = first.Elements().Push(2.0)
	_, _ = second.Elements().Push(3.0)
	one, two := mustPrepare(t, first), mustPrepare(t, second)
	if err := stale.Adopt(one); err != nil {
		t.Fatal(err)
	}
	if err := stale.Adopt(two); err == nil {
		t.Fatal("a competing preparation must be stale")
	}
}

func jsonTextOf(t *testing.T, value any) string {
	t.Helper()
	encoded, err := json.Marshal(value)
	if err != nil {
		t.Fatal(err)
	}
	return string(encoded)
}

type piArrayRootCase struct {
	Seed    int                 `json:"seed"`
	Rows    bool                `json:"rows"`
	Initial []any               `json:"initial"`
	Steps   [][]json.RawMessage `json:"steps"`
	Ops     Ops                 `json:"ops"`
	Value   []any               `json:"value"`
}

func applyArrayRootStep(t *testing.T, root *Array, rows bool, raw []json.RawMessage) {
	t.Helper()
	var kind string
	_ = json.Unmarshal(raw[0], &kind)
	rest := make([]any, len(raw)-1)
	for index, element := range raw[1:] {
		rest[index], _ = DecodeJson(element)
	}
	number := func(index int) int { return int(rest[index].(float64)) }
	must := func(err error) {
		t.Helper()
		if err != nil {
			t.Fatal(err)
		}
	}
	switch kind {
	case "push":
		_, err := root.Push(rest[0].([]any)...)
		must(err)
	case "unshift":
		_, err := root.Unshift(rest[0].([]any)...)
		must(err)
	case "shift":
		root.Shift()
	case "pop":
		root.Pop()
	case "splice":
		_, err := root.Splice(number(0), number(1), rest[2].([]any)...)
		must(err)
	case "reverse":
		root.Reverse()
	case "sort":
		root.Sort(func(a, b any) bool {
			if rows {
				left, right := a.(*Object), b.(*Object)
				if lv, rv := left.Get("value").(float64), right.Get("value").(float64); lv != rv {
					return lv < rv
				}
				return left.Get("id").(float64) < right.Get("id").(float64)
			}
			return a.(float64) < b.(float64)
		})
	case "setIndex":
		must(root.Set(number(0), rest[1]))
	case "rowField":
		must(root.Object(number(0)).Set(rest[1].(string), rest[2]))
	case "tag":
		_, err := root.Object(number(0)).Array("tags").Push(rest[1])
		must(err)
	case "length":
		root.SetLen(number(0))
	default:
		t.Fatalf("unknown step %q", kind)
	}
}

func TestTrackerArrayRootOperationsMatchPiForRandomizedEdits(t *testing.T) {
	data, err := os.ReadFile("testdata/pi_array_root_operations.json")
	if err != nil {
		t.Fatal(err)
	}
	var raw []struct {
		piArrayRootCase
		Initial json.RawMessage `json:"initial"`
		Value   json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		t.Fatal(err)
	}
	// Pi's rows are {id, value, tags} in that order, so the values decode with their key order.
	cases := make([]piArrayRootCase, len(raw))
	for index, entry := range raw {
		cases[index] = entry.piArrayRootCase
		cases[index].Initial = jsonOf(t, string(entry.Initial)).([]any)
		cases[index].Value = jsonOf(t, string(entry.Value)).([]any)
	}
	var failures []string
	for _, c := range cases {
		change := TrackArray(c.Initial).BeginChange()
		for _, raw := range c.Steps {
			applyArrayRootStep(t, change.Elements(), c.Rows, raw)
		}
		prepared, err := change.Prepare()
		if err != nil {
			t.Fatalf("seed %d: %v", c.Seed, err)
		}
		if got, want := jsonTextOf(t, prepared.ValueRoot()), jsonTextOf(t, c.Value); got != want {
			t.Fatalf("seed %d: value %s != Pi %s", c.Seed, got, want)
		}
		if got, want := jsonTextOf(t, prepared.Ops()), jsonTextOf(t, c.Ops); got != want {
			failures = append(failures, fmt.Sprintf("seed %d steps %v\n   Pi %s\n   Go %s", c.Seed, c.Steps, want, got))
		}
	}
	if len(failures) > 0 {
		t.Fatalf("%d of %d cases record different operations than Pi:\n%s", len(failures), len(cases), strings.Join(failures[:min(len(failures), 6)], "\n"))
	}
}

// An empty array has no allocation to compare, so adopting a revision over one must not look stale.
func TestTrackerAdoptsOverAnEmptyArrayRoot(t *testing.T) {
	tracker := TrackArray([]any{})
	for _, push := range []bool{false, true, false} {
		change := tracker.BeginChange()
		if push {
			_, _ = change.Elements().Push(1.0)
		}
		if err := tracker.Adopt(mustPrepare(t, change)); err != nil {
			t.Fatal(err)
		}
	}
	if got := jsonTextOf(t, tracker.Root()); got != `[1]` {
		t.Fatalf("root %s", got)
	}
}
