// Code generated by pig piglet build. DO NOT EDIT.
//
// Stock Pig ships this file empty. A Piglet Binary build may temporarily
// generate imports for compatible extension packages and restores this file.
package fusepack
