// Regenerate the Go schema data and oracle from the exact pinned upstream:
// node agent/harness/testdata/telemetry-schema.mjs --write
import { registerHooks } from 'node:module';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const root = resolve(import.meta.dirname, '../../..');
const source = path => pathToFileURL(resolve(root, '.upstream/current', path)).href;
const aliases = new Map([
  ['@earendil-works/pi-telemetry', 'packages/telemetry/src/index.ts'],
  ['@earendil-works/chord/context', 'packages/chord/src/context/index.ts'],
]);
registerHooks({
  resolve(specifier, context, next) {
    const path = aliases.get(specifier);
    return path ? {url: source(path), shortCircuit: true} : next(specifier, context);
  },
});
const {AGENT_TELEMETRY_SCHEMAS} = await import(source('packages/agent/src/harness/telemetry.ts'));
const json = JSON.stringify(AGENT_TELEMETRY_SCHEMAS, null, 2) + '\n';
if (!process.argv.includes('--write')) {
  process.stdout.write(json);
} else {
  const quote = JSON.stringify;
  const values = array => `[]AttributeValue{${array.map(value => quote(value)).join(', ')}}`;
  const strings = array => `[]string{${array.map(quote).join(', ')}}`;
  const attribute = value => {
    const {type, description, cardinality, values: allowed, elementValues, required, ...rest} = value;
    if (Object.keys(rest).length) throw new Error(`unhandled attribute fields: ${Object.keys(rest)}`);
    return `TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: ${quote(description)}${cardinality ? `, Cardinality: ${quote(cardinality)}` : ''}}, Type: ${quote(type)}${allowed ? `, Values: ${values(allowed)}` : ''}${elementValues ? `, ElementValues: ${values(elementValues)}` : ''}}`;
  };
  const startAttribute = value => `TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: ${attribute(value)}, Required: ${value.required}}`;
  const definitions = (entries, type, render) => `TelemetryDefinitions[${type}]{\n${Object.entries(entries).map(([name, value]) => `{Name: ${quote(name)}, Definition: ${render(value)}},`).join('\n')}\n}`;
  const span = value => {
    const {description, parents, startAttributes, endAttributes, status, ...rest} = value;
    if (Object.keys(rest).length) throw new Error(`unhandled span fields: ${Object.keys(rest)}`);
    return `TelemetrySpanDefinition{
      Description: ${quote(description)},
      Parents: TelemetryParentDefinition{Kind: ${quote(parents.kind)}${parents.spans ? `, Spans: ${strings(parents.spans)}` : ''}},
      StartAttributes: ${definitions(startAttributes, 'TelemetryStartAttributeDefinition', startAttribute)},
      EndAttributes: ${definitions(endAttributes, 'TelemetryAttributeDefinition', attribute)},
      Status: struct { Default SpanStatusCode \`json:"default"\`; ErrorWhen string \`json:"errorWhen"\` }{Default: ${quote(status.default)}, ErrorWhen: ${quote(status.errorWhen)}},
    }`;
  };
  const names = ['AITelemetrySchema', 'HarnessTelemetrySchema'];
  if (AGENT_TELEMETRY_SCHEMAS.length !== names.length) throw new Error('upstream schema tuple changed');
  const declarations = AGENT_TELEMETRY_SCHEMAS.map((schema, i) => `// ${names[i]} describes ${i === 0 ? 'AI-request' : 'harness'} telemetry without enabling recording or export.
var ${names[i]} = TelemetrySchemaDefinition{Version: ${schema.version}, Spans: ${definitions(schema.spans, 'TelemetrySpanDefinition', span)}}`).join('\n\n');
  writeFileSync(resolve(root, 'agent/harness/telemetry_schema_data.go'), `// Code generated by testdata/telemetry-schema.mjs from the pinned upstream harness/telemetry.ts; DO NOT EDIT.

package harness

${declarations}

// AgentTelemetrySchemas combines the AI-request and harness span vocabularies in upstream order.
var AgentTelemetrySchemas = []TelemetrySchemaDefinition{AITelemetrySchema, HarnessTelemetrySchema}
`);
  writeFileSync(resolve(import.meta.dirname, 'telemetry-schema.json'), json);
  execFileSync('gofmt', ['-w', resolve(root, 'agent/harness/telemetry_schema_data.go')]);
}
