// SPDX-License-Identifier: MIT

// Code generated by go generate ./durable/core/abi; DO NOT EDIT.

package abi

//go:generate go run ./spec/cmd/abigen -dir .

// ID is abi_id: the hex sha256 of the canonical rendering of the ABI 1 tables in package spec.
const ID = "f82162f61f856df71b0d2d25a1016666bd3deda899713aa5b1e1c028827d1fa1"
