// Code generated by testdata/telemetry-schema.mjs from the pinned upstream harness/telemetry.ts; DO NOT EDIT.

package harness

// AITelemetrySchema describes AI-request telemetry without enabling recording or export.
var AITelemetrySchema = TelemetrySchemaDefinition{Version: 1, Spans: TelemetryDefinitions[TelemetrySpanDefinition]{
	{Name: "pi.ai.request", Definition: TelemetrySpanDefinition{
		Description: "One logical request to an AI provider",
		Parents:     TelemetryParentDefinition{Kind: "any"},
		StartAttributes: TelemetryDefinitions[TelemetryStartAttributeDefinition]{
			{Name: "pi.ai.operation", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Logical provider operation"}, Type: "string", Values: []AttributeValue{"stream", "fetch_deferred", "cancel_deferred", "generate_images"}}, Required: true}},
			{Name: "pi.ai.provider", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Selected provider id"}, Type: "string"}, Required: true}},
			{Name: "pi.ai.model", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Requested model id"}, Type: "string"}, Required: true}},
			{Name: "pi.ai.api", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Provider API id"}, Type: "string"}, Required: true}},
			{Name: "pi.ai.streaming", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Whether this operation returns a stream"}, Type: "boolean"}, Required: true}},
			{Name: "pi.ai.deferred", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Whether the operation requests or participates in deferred execution"}, Type: "boolean"}, Required: false}},
		},
		EndAttributes: TelemetryDefinitions[TelemetryAttributeDefinition]{
			{Name: "pi.ai.response.model", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Concrete response model"}, Type: "string"}},
			{Name: "pi.ai.response.id", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Provider response id", Cardinality: "high"}, Type: "string"}},
			{Name: "pi.ai.response.stop_reason", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Normalized terminal response reason"}, Type: "string", Values: []AttributeValue{"stop", "length", "tool_use", "error", "aborted", "deferred"}}},
			{Name: "pi.ai.http.status_code", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Final HTTP status"}, Type: "number"}},
			{Name: "pi.ai.usage.input_tokens", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Reported input tokens"}, Type: "number"}},
			{Name: "pi.ai.usage.output_tokens", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Reported output tokens"}, Type: "number"}},
			{Name: "pi.ai.usage.cache_read_tokens", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Reported cache-read tokens"}, Type: "number"}},
			{Name: "pi.ai.usage.cache_write_tokens", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Reported cache-write tokens"}, Type: "number"}},
			{Name: "pi.ai.usage.reasoning_tokens", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Reported reasoning tokens"}, Type: "number"}},
			{Name: "pi.ai.usage.total_tokens", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Reported total tokens"}, Type: "number"}},
			{Name: "pi.ai.usage.cost", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Reported total cost"}, Type: "number"}},
			{Name: "pi.ai.stream.chunk_count", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Streamed update chunk count"}, Type: "number"}},
			{Name: "pi.ai.stream.time_to_first_chunk_ms", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Elapsed milliseconds to first update chunk"}, Type: "number"}},
			{Name: "pi.ai.error.type", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Provider or transport error class", Cardinality: "low"}, Type: "string"}},
		},
		Status: struct {
			Default   SpanStatusCode `json:"default"`
			ErrorWhen string         `json:"errorWhen"`
		}{Default: "ok", ErrorWhen: "The operation throws or returns an error result"},
	}},
}}

// HarnessTelemetrySchema describes harness telemetry without enabling recording or export.
var HarnessTelemetrySchema = TelemetrySchemaDefinition{Version: 1, Spans: TelemetryDefinitions[TelemetrySpanDefinition]{
	{Name: "pi.harness.run", Definition: TelemetrySpanDefinition{
		Description: "One admitted in-process run invocation",
		Parents:     TelemetryParentDefinition{Kind: "root_or_external"},
		StartAttributes: TelemetryDefinitions[TelemetryStartAttributeDefinition]{
			{Name: "pi.session.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Session id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.lane.name", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Lane name", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.operation.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Durable operation id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.operation.recovery", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Whether this invocation resumes durable work"}, Type: "boolean"}, Required: true}},
			{Name: "pi.operation.kind", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Run operation kind"}, Type: "string", Values: []AttributeValue{"run"}}, Required: true}},
		},
		EndAttributes: TelemetryDefinitions[TelemetryAttributeDefinition]{
			{Name: "pi.operation.outcome", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Run invocation outcome"}, Type: "string", Values: []AttributeValue{"completed", "aborted", "failed", "suspended"}}},
			{Name: "pi.error.code", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Stable operation error code", Cardinality: "low"}, Type: "string"}},
			{Name: "pi.error.type", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Low-cardinality operation error class", Cardinality: "low"}, Type: "string"}},
		},
		Status: struct {
			Default   SpanStatusCode `json:"default"`
			ErrorWhen string         `json:"errorWhen"`
		}{Default: "ok", ErrorWhen: "The run fails or throws"},
	}},
	{Name: "pi.harness.compaction", Definition: TelemetrySpanDefinition{
		Description: "One admitted in-process manual compaction invocation",
		Parents:     TelemetryParentDefinition{Kind: "root_or_external"},
		StartAttributes: TelemetryDefinitions[TelemetryStartAttributeDefinition]{
			{Name: "pi.session.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Session id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.lane.name", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Lane name", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.operation.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Durable operation id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.operation.recovery", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Whether this invocation resumes durable work"}, Type: "boolean"}, Required: true}},
			{Name: "pi.operation.kind", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Compaction operation kind"}, Type: "string", Values: []AttributeValue{"compaction"}}, Required: true}},
		},
		EndAttributes: TelemetryDefinitions[TelemetryAttributeDefinition]{
			{Name: "pi.operation.outcome", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Compaction invocation outcome"}, Type: "string", Values: []AttributeValue{"completed", "declined", "aborted", "failed"}}},
			{Name: "pi.error.code", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Stable operation error code", Cardinality: "low"}, Type: "string"}},
			{Name: "pi.error.type", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Low-cardinality operation error class", Cardinality: "low"}, Type: "string"}},
		},
		Status: struct {
			Default   SpanStatusCode `json:"default"`
			ErrorWhen string         `json:"errorWhen"`
		}{Default: "ok", ErrorWhen: "The compaction fails or throws"},
	}},
	{Name: "pi.harness.navigation", Definition: TelemetrySpanDefinition{
		Description: "One admitted in-process navigation invocation",
		Parents:     TelemetryParentDefinition{Kind: "root_or_external"},
		StartAttributes: TelemetryDefinitions[TelemetryStartAttributeDefinition]{
			{Name: "pi.session.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Session id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.lane.name", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Lane name", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.operation.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Durable operation id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.operation.recovery", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Whether this invocation resumes durable work"}, Type: "boolean"}, Required: true}},
			{Name: "pi.operation.kind", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Navigation operation kind"}, Type: "string", Values: []AttributeValue{"navigation"}}, Required: true}},
		},
		EndAttributes: TelemetryDefinitions[TelemetryAttributeDefinition]{
			{Name: "pi.operation.outcome", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Navigation invocation outcome"}, Type: "string", Values: []AttributeValue{"completed", "declined", "aborted", "failed"}}},
			{Name: "pi.error.code", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Stable operation error code", Cardinality: "low"}, Type: "string"}},
			{Name: "pi.error.type", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Low-cardinality operation error class", Cardinality: "low"}, Type: "string"}},
		},
		Status: struct {
			Default   SpanStatusCode `json:"default"`
			ErrorWhen string         `json:"errorWhen"`
		}{Default: "ok", ErrorWhen: "The navigation fails or throws"},
	}},
	{Name: "pi.harness.checkpoint", Definition: TelemetrySpanDefinition{
		Description: "One run checkpoint",
		Parents:     TelemetryParentDefinition{Kind: "spans", Spans: []string{"pi.harness.run"}},
		StartAttributes: TelemetryDefinitions[TelemetryStartAttributeDefinition]{
			{Name: "pi.lane.name", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Lane name", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.operation.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Durable operation id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.checkpoint.kind", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Checkpoint purpose"}, Type: "string", Values: []AttributeValue{"normal", "abort_reconcile"}}, Required: true}},
		},
		EndAttributes: TelemetryDefinitions[TelemetryAttributeDefinition]{},
		Status: struct {
			Default   SpanStatusCode `json:"default"`
			ErrorWhen string         `json:"errorWhen"`
		}{Default: "ok", ErrorWhen: "Checkpoint work throws"},
	}},
	{Name: "pi.harness.turn", Definition: TelemetrySpanDefinition{
		Description: "One assistant response and its tool batch",
		Parents:     TelemetryParentDefinition{Kind: "spans", Spans: []string{"pi.harness.run"}},
		StartAttributes: TelemetryDefinitions[TelemetryStartAttributeDefinition]{
			{Name: "pi.lane.name", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Lane name", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.operation.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Durable operation id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.turn.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Invocation-local turn id", Cardinality: "high"}, Type: "string"}, Required: true}},
		},
		EndAttributes: TelemetryDefinitions[TelemetryAttributeDefinition]{},
		Status: struct {
			Default   SpanStatusCode `json:"default"`
			ErrorWhen string         `json:"errorWhen"`
		}{Default: "ok", ErrorWhen: "Turn work throws"},
	}},
	{Name: "pi.harness.step", Definition: TelemetrySpanDefinition{
		Description: "One durable retry attempt",
		Parents:     TelemetryParentDefinition{Kind: "spans", Spans: []string{"pi.harness.turn", "pi.harness.checkpoint", "pi.harness.compaction", "pi.harness.navigation"}},
		StartAttributes: TelemetryDefinitions[TelemetryStartAttributeDefinition]{
			{Name: "pi.lane.name", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Lane name", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.operation.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Durable operation id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.step.kind", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Retryable step kind"}, Type: "string", Values: []AttributeValue{"assistant", "compaction", "branch_summary"}}, Required: true}},
			{Name: "pi.step.attempt", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "One-based durable attempt number"}, Type: "number"}, Required: true}},
			{Name: "pi.compaction.reason", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Compaction trigger"}, Type: "string", Values: []AttributeValue{"manual", "threshold", "overflow"}}, Required: false}},
		},
		EndAttributes: TelemetryDefinitions[TelemetryAttributeDefinition]{
			{Name: "pi.step.outcome", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Attempt outcome"}, Type: "string", Values: []AttributeValue{"succeeded", "retry", "failed", "aborted", "deferred", "overflow"}}},
		},
		Status: struct {
			Default   SpanStatusCode `json:"default"`
			ErrorWhen string         `json:"errorWhen"`
		}{Default: "ok", ErrorWhen: "The attempt retries, fails, or throws"},
	}},
	{Name: "pi.harness.tool", Definition: TelemetrySpanDefinition{
		Description: "One raw phase-2 tool execution",
		Parents:     TelemetryParentDefinition{Kind: "spans", Spans: []string{"pi.harness.turn", "pi.harness.run"}},
		StartAttributes: TelemetryDefinitions[TelemetryStartAttributeDefinition]{
			{Name: "pi.lane.name", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Lane name", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.operation.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Durable operation id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.turn.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Invocation-local live turn id", Cardinality: "high"}, Type: "string"}, Required: false}},
			{Name: "pi.tool.name", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Tool name"}, Type: "string"}, Required: true}},
			{Name: "pi.tool.call_id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Tool call id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.tool.replay", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Declared replay policy"}, Type: "string", Values: []AttributeValue{"never", "safe"}}, Required: true}},
			{Name: "pi.tool.recovery", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Whether this is recovery execution"}, Type: "boolean"}, Required: true}},
		},
		EndAttributes: TelemetryDefinitions[TelemetryAttributeDefinition]{
			{Name: "pi.tool.is_error", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Whether raw phase-2 execution returned an error"}, Type: "boolean"}},
		},
		Status: struct {
			Default   SpanStatusCode `json:"default"`
			ErrorWhen string         `json:"errorWhen"`
		}{Default: "ok", ErrorWhen: "Raw phase-2 execution returns an error"},
	}},
	{Name: "pi.harness.hook", Definition: TelemetrySpanDefinition{
		Description: "One registered hook handler invocation",
		Parents:     TelemetryParentDefinition{Kind: "any"},
		StartAttributes: TelemetryDefinitions[TelemetryStartAttributeDefinition]{
			{Name: "pi.lane.name", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Lane name", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.operation.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Durable operation id when accepted", Cardinality: "high"}, Type: "string"}, Required: false}},
			{Name: "pi.hook.name", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Hook name"}, Type: "string", Values: []AttributeValue{"before_run", "before_drive", "before_run_end", "transform_context", "before_request", "before_payload", "after_response", "before_tool", "after_tool", "before_compaction", "before_navigation"}}, Required: true}},
			{Name: "pi.hook.registration_id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Optional hook registration metadata"}, Type: "string"}, Required: false}},
		},
		EndAttributes: TelemetryDefinitions[TelemetryAttributeDefinition]{
			{Name: "pi.hook.outcome", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Handler outcome"}, Type: "string", Values: []AttributeValue{"completed", "skipped", "blocked", "failed"}}},
		},
		Status: struct {
			Default   SpanStatusCode `json:"default"`
			ErrorWhen string         `json:"errorWhen"`
		}{Default: "ok", ErrorWhen: "The handler throws"},
	}},
	{Name: "pi.harness.sleep", Definition: TelemetrySpanDefinition{
		Description: "One retry delay",
		Parents:     TelemetryParentDefinition{Kind: "spans", Spans: []string{"pi.harness.run", "pi.harness.compaction", "pi.harness.navigation", "pi.harness.turn", "pi.harness.checkpoint"}},
		StartAttributes: TelemetryDefinitions[TelemetryStartAttributeDefinition]{
			{Name: "pi.operation.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Durable operation id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.sleep.delay_ms", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Requested delay in milliseconds"}, Type: "number"}, Required: true}},
		},
		EndAttributes: TelemetryDefinitions[TelemetryAttributeDefinition]{
			{Name: "pi.sleep.outcome", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Delay outcome"}, Type: "string", Values: []AttributeValue{"elapsed", "aborted"}}},
		},
		Status: struct {
			Default   SpanStatusCode `json:"default"`
			ErrorWhen string         `json:"errorWhen"`
		}{Default: "ok", ErrorWhen: "Sleep work throws"},
	}},
	{Name: "pi.harness.event_handler", Definition: TelemetrySpanDefinition{
		Description: "One passive event listener invocation",
		Parents:     TelemetryParentDefinition{Kind: "any"},
		StartAttributes: TelemetryDefinitions[TelemetryStartAttributeDefinition]{
			{Name: "pi.event.type", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Delivered harness event type", Cardinality: "low"}, Type: "string", Values: []AttributeValue{"run_start", "run_resume", "run_suspend", "operation_abort", "run_end", "fault", "handler_error", "turn_start", "turn_end", "retry_scheduled", "retry_start", "retry_end", "message_start", "message_update", "message_end", "tool_start", "tool_update", "tool_end", "entry_added", "queue_update", "value_update", "config_update", "compaction_start", "compaction_end", "navigation_start", "navigation_end", "lane_created", "usage"}}, Required: true}},
			{Name: "pi.lane.name", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Lane name for lane-scoped events", Cardinality: "high"}, Type: "string"}, Required: false}},
		},
		EndAttributes: TelemetryDefinitions[TelemetryAttributeDefinition]{},
		Status: struct {
			Default   SpanStatusCode `json:"default"`
			ErrorWhen string         `json:"errorWhen"`
		}{Default: "ok", ErrorWhen: "The listener throws"},
	}},
	{Name: "pi.session.write", Definition: TelemetrySpanDefinition{
		Description: "One committed session transaction",
		Parents:     TelemetryParentDefinition{Kind: "any"},
		StartAttributes: TelemetryDefinitions[TelemetryStartAttributeDefinition]{
			{Name: "pi.session.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Session id", Cardinality: "high"}, Type: "string"}, Required: true}},
			{Name: "pi.lane.name", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Lane name when supplied by the caller", Cardinality: "high"}, Type: "string"}, Required: false}},
			{Name: "pi.operation.id", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Durable operation id when supplied by the caller", Cardinality: "high"}, Type: "string"}, Required: false}},
			{Name: "pi.session.item_count", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Number of writes in the transaction"}, Type: "number"}, Required: true}},
			{Name: "pi.session.item_kinds", Definition: TelemetryStartAttributeDefinition{TelemetryAttributeDefinition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Distinct write kinds in the transaction"}, Type: "string[]", ElementValues: []AttributeValue{"entry", "usage", "value", "list"}}, Required: true}},
		},
		EndAttributes: TelemetryDefinitions[TelemetryAttributeDefinition]{
			{Name: "pi.session.first_seq", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "First committed sequence in the transaction"}, Type: "number"}},
			{Name: "pi.session.last_seq", Definition: TelemetryAttributeDefinition{TelemetryAttributeMetadata: TelemetryAttributeMetadata{Description: "Last committed sequence in the transaction"}, Type: "number"}},
		},
		Status: struct {
			Default   SpanStatusCode `json:"default"`
			ErrorWhen string         `json:"errorWhen"`
		}{Default: "ok", ErrorWhen: "Storage rejects the transaction"},
	}},
}}

// AgentTelemetrySchemas combines the AI-request and harness span vocabularies in upstream order.
var AgentTelemetrySchemas = []TelemetrySchemaDefinition{AITelemetrySchema, HarnessTelemetrySchema}
