package compaction

import (
	"bytes"
	"encoding/json"
	"math/rand"
	"os/exec"
	"reflect"
	"testing"

	"github.com/MichaelKinsy/PiG/internal/coding/pigversion"
	"github.com/MichaelKinsy/PiG/internal/codingagent"
	"github.com/MichaelKinsy/PiG/internal/sessionentry"
)

// pi: packages/coding-agent/src/core/compaction/branch-summarization.ts

// collectEntriesForBranchSummary and prepareBranchEntries (branch-summarization.ts:30-170) over generated session trees (the entries of the
// compaction oracle with random parents, so branches fork) and token budgets: the entries to summarize and the common ancestor, then the
// messages kept within the budget, the file operations (also from earlier branch summaries' details, unless generated by a hook) and the tokens.
func TestBranchSummaryEntriesMatchPi(t *testing.T) {
	rng := rand.New(rand.NewSource(21))
	type testCase struct {
		Entries []json.RawMessage `json:"entries"`
		Budget  int               `json:"budget"`
		OldLeaf *string           `json:"oldLeaf"`
		Target  *string           `json:"target"`
	}
	var cases []testCase
	for range 1500 {
		entries := generateSessionPath(rng)
		// Fork the chain: every entry after the first takes a random earlier entry as its parent.
		for i := 1; i < len(entries); i++ {
			if rng.Intn(3) == 0 {
				var entry map[string]any
				if err := json.Unmarshal(entries[i], &entry); err != nil {
					t.Fatal(err)
				}
				entry["parentId"] = []string{"1", "2", "3", "4", "5", "6"}[rng.Intn(min(i, 6))]
				encoded, _ := json.Marshal(entry)
				entries[i] = encoded
			}
		}
		pickID := func() *string {
			if len(entries) == 0 || rng.Intn(12) == 0 {
				id := []string{"", "zz", "1"}[rng.Intn(3)]
				if id == "" {
					return nil
				}
				return &id
			}
			var entry struct{ ID string }
			_ = json.Unmarshal(entries[rng.Intn(len(entries))], &entry)
			return &entry.ID
		}
		cases = append(cases, testCase{Entries: entries, Budget: []int{0, 0, 1, 10, 50, 200, 1000, 5000}[rng.Intn(8)], OldLeaf: pickID(), Target: pickID()})
	}
	input, err := json.Marshal(cases)
	if err != nil {
		t.Fatal(err)
	}
	cmd := exec.CommandContext(t.Context(), "node", "testdata/branch_summary_pi.mjs", pigversion.UpstreamVersion)
	cmd.Stdin = bytes.NewReader(input)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	output, err := cmd.Output()
	if err != nil {
		t.Fatalf("Pi oracle: %v\n%s", err, &stderr)
	}
	var want []map[string]any
	if err := json.Unmarshal(output, &want); err != nil {
		t.Fatal(err)
	}
	roundTrip := func(value any) any {
		encoded, err := json.Marshal(value)
		if err != nil {
			t.Fatal(err)
		}
		var out any
		_ = json.Unmarshal(encoded, &out)
		return out
	}
	failures := 0
	for i, c := range cases {
		entries := make([]codingagent.SessionEntry, len(c.Entries))
		for j, raw := range c.Entries {
			entries[j] = sessionentry.DecodeSessionEntry(raw)
		}
		oldLeaf, target := "", ""
		if c.OldLeaf != nil {
			oldLeaf = *c.OldLeaf
		}
		if c.Target != nil {
			target = *c.Target
		}
		session := fakeSession{entries: entries}
		collected := CollectEntriesForBranchSummary(session, oldLeaf, target)
		ids := []any{}
		for _, entry := range collected.Entries {
			ids = append(ids, entry.Base().ID)
		}
		var common any
		if collected.CommonAncestorID != "" {
			common = collected.CommonAncestorID
		}
		prepared := PrepareBranchEntries(entries, c.Budget)
		messages := roundTrip(prepared.Messages)
		if messages == nil {
			messages = []any{}
		}
		got := map[string]any{
			"collect": map[string]any{"ok": map[string]any{"ids": ids, "common": common}},
			"prepare": map[string]any{"ok": map[string]any{"messages": messages, "fileOps": roundTrip(prepared.FileOps), "totalTokens": float64(prepared.TotalTokens)}},
		}
		for key := range got {
			if !reflect.DeepEqual(got[key], want[i][key]) {
				if failures++; failures <= 5 {
					t.Errorf("case %d %s (budget %d old %v target %v): %s\n entries %.2500s", i, key, c.Budget, c.OldLeaf, c.Target, firstDiff(key, got[key], want[i][key]), oracleJSON(c.Entries))
				}
			}
		}
	}
	if failures > 5 {
		t.Errorf("%d differences from Pi", failures)
	}
}

// fakeSession is the read-only session of the oracle: entries by id and the root-first path to one.
type fakeSession struct{ entries []codingagent.SessionEntry }

func (s fakeSession) GetEntry(id string) (codingagent.SessionEntry, bool) {
	for _, entry := range s.entries {
		if entry.Base().ID == id {
			return entry, true
		}
	}
	return nil, false
}

func (s fakeSession) GetBranch(from ...string) []codingagent.SessionEntry {
	if len(from) == 0 {
		return nil
	}
	var path []codingagent.SessionEntry
	current, ok := s.GetEntry(from[0])
	for ok {
		path = append([]codingagent.SessionEntry{current}, path...)
		parent := current.Base().ParentID
		if parent == nil {
			break
		}
		current, ok = s.GetEntry(*parent)
	}
	return path
}
