// Command gen-classifier-models imports the CLASSIFIER_MODELS export of a published Pi models.generated.js and emits
// ai/classifier_models_generated.go.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"slices"
	"strings"
)

type classifierModel struct {
	Type          string            `json:"type"`
	ID            string            `json:"id"`
	Name          string            `json:"name"`
	API           string            `json:"api"`
	Provider      string            `json:"provider"`
	BaseURL       string            `json:"baseUrl"`
	Headers       map[string]string `json:"headers,omitempty"`
	Input         []string          `json:"input"`
	ContextWindow int               `json:"contextWindow"`
	Cost          struct {
		Input      float64 `json:"input"`
		Output     float64 `json:"output"`
		CacheRead  float64 `json:"cacheRead"`
		CacheWrite float64 `json:"cacheWrite"`
	} `json:"cost"`
}

func main() {
	src := flag.String("src", "", "published models.generated.js")
	out := flag.String("out", "ai/classifier_models_generated.go", "generated Go output")
	flag.Parse()
	if *src == "" {
		fatal(fmt.Errorf("-src is required"))
	}
	models, err := load(*src)
	if err != nil {
		fatal(err)
	}
	data, err := render(models)
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		fatal(err)
	}
	fmt.Fprintf(os.Stderr, "gen-classifier-models: wrote %d models to %s\n", len(models), *out)
}

// load returns the classifier models by provider name, each provider's models in the published catalog's order.
func load(path string) ([]classifierModel, error) {
	script := `import { pathToFileURL } from "node:url";
const mod = await import(pathToFileURL(process.argv[1]).href);
process.stdout.write(JSON.stringify(Object.entries(mod.CLASSIFIER_MODELS).map(([provider, models]) => [provider, Object.entries(models).map(([id, model]) => [id, model])])));`
	data, err := exec.Command("node", "--input-type=module", "-e", script, path).CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("import published classifier catalog: %w\n%s", err, data)
	}
	var raw [][2]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("decode classifier catalog: %w", err)
	}
	var out []classifierModel
	type entry struct {
		provider string
		models   []classifierModel
	}
	var entries []entry
	for _, provider := range raw {
		var name string
		if err := json.Unmarshal(provider[0], &name); err != nil {
			return nil, err
		}
		var pairs [][2]json.RawMessage
		if err := json.Unmarshal(provider[1], &pairs); err != nil {
			return nil, err
		}
		current := entry{provider: name}
		for _, pair := range pairs {
			var id string
			if err := json.Unmarshal(pair[0], &id); err != nil {
				return nil, err
			}
			var model classifierModel
			decoder := json.NewDecoder(bytes.NewReader(pair[1]))
			decoder.DisallowUnknownFields()
			if err := decoder.Decode(&model); err != nil {
				return nil, fmt.Errorf("decode %s/%s: %w", name, id, err)
			}
			if model.ID != id || model.Provider != name || model.Type != "classifier" {
				return nil, fmt.Errorf("catalog key %s/%s disagrees with model %s/%s (%s)", name, id, model.Provider, model.ID, model.Type)
			}
			current.models = append(current.models, model)
		}
		entries = append(entries, current)
	}
	slices.SortStableFunc(entries, func(a, b entry) int { return strings.Compare(a.provider, b.provider) })
	for _, current := range entries {
		out = append(out, current.models...)
	}
	return out, nil
}

func render(models []classifierModel) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by gen-classifier-models. DO NOT EDIT.\n")
	b.WriteString("package ai\n\n")
	fmt.Fprintf(&b, "// GeneratedClassifierModels is the static classifier model catalog (%d entries).\n", len(models))
	b.WriteString("var GeneratedClassifierModels = []ClassifierModel{\n")
	for _, model := range models {
		fmt.Fprintf(&b, "{ID:%q, Name:%q, API:ClassifierAPI(%q), Provider:%q, BaseURL:%q,", model.ID, model.Name, model.API, model.Provider, model.BaseURL)
		if len(model.Headers) > 0 {
			keys := make([]string, 0, len(model.Headers))
			for key := range model.Headers {
				keys = append(keys, key)
			}
			slices.Sort(keys)
			b.WriteString(" Headers:map[string]string{")
			for _, key := range keys {
				fmt.Fprintf(&b, "%q:%q,", key, model.Headers[key])
			}
			b.WriteString("},")
		}
		fmt.Fprintf(&b, " Input:%#v, ContextWindow:%d, Cost:ModelCost{Input:%v, Output:%v, CacheRead:%v, CacheWrite:%v}},\n",
			model.Input, model.ContextWindow, model.Cost.Input, model.Cost.Output, model.Cost.CacheRead, model.Cost.CacheWrite)
	}
	b.WriteString("}\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated catalog: %w", err)
	}
	return formatted, nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gen-classifier-models:", err)
	os.Exit(1)
}
