// Command genstripids writes internal/pigstrip/ids_generated.go, the table of
// stable IDs a Piglet strip list may name. It reads the IDs from the
// registrations themselves: the built-in tool registry, the built-in slash
// command list with the Piglet extension's /piglet command, the built-in
// extension list, the strippable API list and the strippable feature list.
// A renamed registration changes the table, so a Piglet that names the old ID
// fails to resolve instead of silently stripping nothing.
//
// Usage: go run ./coding/piglet/internal/genstripids [-check | -print-tags]
//
// -print-tags prints the comma-separated build tags of every strip ID a Piglet
// Binary can compile out (make piglet-strip-build builds and vets with them).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"slices"
	"strings"

	"github.com/MichaelKinsy/PiG/ai"
	"github.com/MichaelKinsy/PiG/coding/extension/builtin"
	piglet "github.com/MichaelKinsy/PiG/coding/piglet"
	"github.com/MichaelKinsy/PiG/internal/codingagent"
	agenttools "github.com/MichaelKinsy/PiG/internal/codingagent/tools"
	"github.com/MichaelKinsy/PiG/internal/pigstrip"
)

const defaultOutput = "internal/pigstrip/ids_generated.go"

// parityHarnessEnv adds parity probe commands to the built-in command list. The
// table describes the shipped command set, so the generator clears it.
const parityHarnessEnv = "PIG_PARITY_HARNESS"

func main() {
	check := flag.Bool("check", false, "fail when the committed table differs from the registrations")
	output := flag.String("out", defaultOutput, "generated Go file")
	printTags := flag.Bool("print-tags", false, "print the build tags of every strip ID a Piglet Binary compiles out")
	flag.Parse()
	if *printTags {
		fmt.Println(strings.Join(piglet.StripBuildTags(), ","))
		return
	}
	if err := run(*output, *check); err != nil {
		fmt.Fprintln(os.Stderr, "genstripids:", err)
		os.Exit(1)
	}
}

func run(output string, check bool) error {
	if err := os.Unsetenv(parityHarnessEnv); err != nil {
		return err
	}
	rendered, err := render(collect())
	if err != nil {
		return err
	}
	if check {
		current, err := os.ReadFile(output)
		if err != nil {
			return err
		}
		if !bytes.Equal(current, rendered) {
			return fmt.Errorf("%s is stale; run `make piglet-strip-ids`", output)
		}
		return nil
	}
	return os.WriteFile(output, rendered, 0o644)
}

type table struct {
	tools, commands, extensions, apis, features []string
}

func collect() table {
	var commands []string
	for _, command := range codingagent.BuiltinSlashCommands() {
		commands = append(commands, "/"+command.Name)
	}
	commands = append(commands, "/"+piglet.InspectCommand)
	extensions := []string{strings.TrimPrefix(codingagent.LlamaExtensionPath, codingagent.BuiltinPathPrefix)}
	for _, entry := range builtin.All(builtin.Options{}) {
		extensions = append(extensions, entry.Name)
	}
	var apis []string
	for _, api := range ai.StrippableAPIs() {
		apis = append(apis, string(api))
	}
	return table{
		tools:      sorted(agenttools.BuiltinToolNames()),
		commands:   sorted(commands),
		extensions: sorted(extensions),
		apis:       sorted(apis),
		features:   sorted(pigstrip.Features()),
	}
}

func sorted(values []string) []string {
	out := slices.Clone(values)
	slices.Sort(out)
	return slices.Compact(out)
}

func render(t table) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by go run ./coding/piglet/internal/genstripids; DO NOT EDIT.\n\n")
	b.WriteString("package pigstrip\n\n")
	b.WriteString("// knownIDs are the stable IDs each strip list may name, read from the registrations.\n")
	b.WriteString("var knownIDs = map[string][]string{\n")
	for _, list := range []struct {
		name string
		ids  []string
	}{
		{"ListTools", t.tools},
		{"ListCommands", t.commands},
		{"ListExtensions", t.extensions},
		{"ListAPIs", t.apis},
		{"ListFeatures", t.features},
	} {
		fmt.Fprintf(&b, "\t%s: {\n", list.name)
		for _, id := range list.ids {
			fmt.Fprintf(&b, "\t\t%q,\n", id)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}
