package hljs

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"encoding/json"
	"fmt"
	"io"
	"slices"
	"strings"
	"sync"
	"unicode/utf8"
)

// The grammar snapshots are generated by automation/gen/generate-highlight-grammars.mjs from the exact published Pi package.
//
//go:embed grammars_eager.json.gz
var eagerGrammars []byte

//go:embed grammars_all.json.gz
var allGrammars []byte

// Registry is one highlight.js instance: its registered languages, aliases and every grammar object they reach. Highlighting compiles and mutates those objects, as highlight.js does, so a Registry serializes its callers.
type Registry struct {
	mu        sync.Mutex
	languages map[string]*Mode
	order     []string
	aliases   map[string]string
	nodes     []any
	allLoaded bool
}

// NewRegistry returns a registry with the languages Pi's syntax-highlight module registers when it loads.
func NewRegistry() *Registry {
	r := &Registry{languages: map[string]*Mode{}, aliases: map[string]string{}}
	snapshot := decodeSnapshot(eagerGrammars)
	r.registerSnapshot(snapshot)
	return r
}

// LoadAllLanguages registers the complete language set, as Pi's loadAllHighlightLanguages imports highlight.js/lib/index.js. Later calls do nothing.
func (r *Registry) LoadAllLanguages() {
	snapshot := decodeSnapshot(allGrammars)
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.allLoaded {
		return
	}
	r.allLoaded = true
	r.registerSnapshot(snapshot)
}

// SupportsLanguage is syntax-highlight.ts supportsLanguage: hljs.getLanguage(name) !== undefined.
func (r *Registry) SupportsLanguage(name string) bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.getLanguage(name) != nil
}

// Highlight is hljs.highlight(code, { language, ignoreIllegals }).value. An error is an exception highlight.js throws out of highlight: an unknown language, or a grammar that fails to compile.
func (r *Registry) Highlight(code, language string, ignoreIllegals bool) (html string, err error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	defer func() {
		if recovered := recover(); recovered != nil {
			thrown, ok := recovered.(*hljsError)
			if !ok {
				panic(recovered)
			}
			err = fmt.Errorf("%s", thrown.message)
		}
	}()
	return r.highlight(language, stringToUnits(code), ignoreIllegals, nil).Value, nil
}

// HighlightAuto is hljs.highlightAuto(code, languageSubset).value; a nil subset considers every registered language.
func (r *Registry) HighlightAuto(code string, languageSubset []string) (html string, err error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	defer func() {
		if recovered := recover(); recovered != nil {
			thrown, ok := recovered.(*hljsError)
			if !ok {
				panic(recovered)
			}
			err = fmt.Errorf("%s", thrown.message)
		}
	}()
	return r.highlightAuto(stringToUnits(code), languageSubset).Value, nil
}

// Languages is hljs.listLanguages: the registered names in registration order.
func (r *Registry) Languages() []string {
	r.mu.Lock()
	defer r.mu.Unlock()
	return slices.Clone(r.order)
}

// getLanguage is hljs.getLanguage: the name lowercased, then a registered name or an alias.
func (r *Registry) getLanguage(name string) *Mode {
	name = toLowerCase(name)
	if language := r.languages[name]; language != nil {
		return language
	}
	if alias, ok := r.aliases[name]; ok {
		return r.languages[alias]
	}
	return nil
}

// registerLanguage is hljs.registerLanguage after the language definition has run.
func (r *Registry) registerLanguage(name string, language *Mode) {
	if language.name == "" {
		language.name = name
		language.present |= keyName
	}
	if _, ok := r.languages[name]; !ok {
		r.order = append(r.order, name)
	}
	r.languages[name] = language
	for _, alias := range language.aliases {
		r.aliases[toLowerCase(alias)] = name
	}
}

type snapshot struct {
	FirstNode     int               `json:"firstNode"`
	Nodes         []snapshotNode    `json:"nodes"`
	Registrations [][2]any          `json:"registrations"`
	SystemSymbols []string          `json:"systemSymbols"`
	Canonicalize  [][2]int          `json:"canonicalize"`
	LowerCase     []json.RawMessage `json:"lowerCase"`
}

type snapshotNode struct {
	Kind   string   `json:"k"`
	Props  [][2]any `json:"p"`
	Frozen bool     `json:"frozen"`
}

func decodeSnapshot(data []byte) *snapshot {
	reader, err := gzip.NewReader(bytes.NewReader(data))
	if err != nil {
		panic(fmt.Sprintf("hljs: grammar snapshot: %v", err))
	}
	raw, err := io.ReadAll(reader)
	if err != nil {
		panic(fmt.Sprintf("hljs: grammar snapshot: %v", err))
	}
	var s snapshot
	if err := json.Unmarshal(raw, &s); err != nil {
		panic(fmt.Sprintf("hljs: grammar snapshot: %v", err))
	}
	return &s
}

// registerSnapshot materializes a snapshot's objects, links their references and replays its registrations in order.
func (r *Registry) registerSnapshot(s *snapshot) {
	if s.FirstNode != len(r.nodes) {
		panic(fmt.Sprintf("hljs: grammar snapshot starts at node %d, registry has %d", s.FirstNode, len(r.nodes)))
	}
	for _, node := range s.Nodes {
		switch node.Kind {
		case "mode":
			r.nodes = append(r.nodes, &Mode{frozen: node.Frozen})
		case "keywords":
			r.nodes = append(r.nodes, &keywordsObject{})
		case "aliases":
			r.nodes = append(r.nodes, map[string]string{})
		default:
			panic("hljs: unknown grammar node kind " + node.Kind)
		}
	}
	for i, node := range s.Nodes {
		target := r.nodes[s.FirstNode+i]
		for _, prop := range node.Props {
			key, _ := prop[0].(string)
			switch target := target.(type) {
			case *Mode:
				r.decodeModeProperty(target, key, prop[1])
			case *keywordsObject:
				decodeKeywordsProperty(target, key, prop[1])
			case map[string]string:
				target[key] = prop[1].(string)
			}
		}
	}
	for _, registration := range s.Registrations {
		name, _ := registration[0].(string)
		r.registerLanguage(name, r.nodes[int(registration[1].(float64))].(*Mode))
	}
}

func (r *Registry) ref(value any) any {
	object, ok := value.(map[string]any)
	if !ok {
		return nil
	}
	id, ok := object["ref"].(float64)
	if !ok {
		return nil
	}
	return r.nodes[int(id)]
}

func isUndefined(value any) bool {
	object, ok := value.(map[string]any)
	return ok && object["undef"] == true
}

func decodePattern(value any) pattern {
	switch v := value.(type) {
	case string:
		return stringPattern(v)
	case map[string]any:
		if source, ok := v["re"].(string); ok {
			return regExpPattern(source)
		}
		if list, ok := v["arr"].([]any); ok {
			p := pattern{kind: patternList}
			for _, item := range list {
				p.list = append(p.list, decodePattern(item))
			}
			return p
		}
	case nil, bool:
		if v == true {
			panic("hljs: a pattern property is true")
		}
	}
	return pattern{}
}

func decodeStrings(value any) []string {
	switch v := value.(type) {
	case string:
		return []string{v}
	case map[string]any:
		list, _ := v["arr"].([]any)
		out := make([]string, len(list))
		for i, item := range list {
			out[i] = item.(string)
		}
		return out
	}
	return nil
}

func (r *Registry) decodeModeProperty(mode *Mode, key string, value any) {
	bit, ok := modePropertyKeys[key]
	if !ok {
		panic("hljs: unknown mode property " + key)
	}
	mode.present |= bit
	if isUndefined(value) {
		return
	}
	switch key {
	case "begin":
		mode.begin = decodePattern(value)
	case "end":
		mode.end = decodePattern(value)
	case "match":
		mode.match = decodePattern(value)
	case "illegal":
		mode.illegal = decodePattern(value)
	case "lexemes":
		mode.lexemes = decodePattern(value)
	case "beforeMatch":
		mode.beforeMatch = decodePattern(value)
	case "className":
		mode.className, _ = value.(string)
	case "contains":
		object, _ := value.(map[string]any)
		if list, ok := object["arr"].([]any); ok {
			mode.contains = make([]modeRef, len(list))
			for i, item := range list {
				if item == "self" {
					mode.contains[i] = modeRef{self: true}
					continue
				}
				mode.contains[i] = modeRef{mode: r.ref(item).(*Mode)}
			}
		}
	case "variants":
		object, _ := value.(map[string]any)
		if list, ok := object["arr"].([]any); ok {
			mode.hasVariants = true
			mode.variants = make([]*Mode, len(list))
			for i, item := range list {
				mode.variants[i] = r.ref(item).(*Mode)
			}
		}
	case "starts":
		if starts, ok := r.ref(value).(*Mode); ok {
			mode.starts = starts
		}
	case "endsParent":
		mode.endsParent = value == true
	case "endsWithParent":
		mode.endsWithParent = value == true
	case "excludeBegin":
		mode.excludeBegin = value == true
	case "excludeEnd":
		mode.excludeEnd = value == true
	case "returnBegin":
		mode.returnBegin = value == true
	case "returnEnd":
		mode.returnEnd = value == true
	case "skip":
		mode.skip = value == true
	case "endSameAsBegin":
		mode.endSameAsBegin = value == true
	case "relevance":
		mode.relevance, mode.hasRelevance = value.(float64)
	case "keywords":
		switch v := value.(type) {
		case string:
			mode.keywords = keywordsValue{kind: keywordsKindString, text: v}
		case map[string]any:
			if object, ok := r.ref(v).(*keywordsObject); ok {
				mode.keywords = keywordsValue{kind: keywordsKindObject, object: object}
			} else {
				mode.keywords = keywordsValue{kind: keywordsKindList, list: decodeStrings(v)}
			}
		}
	case "beginKeywords":
		mode.beginKeywords, _ = value.(string)
	case "subLanguage":
		switch v := value.(type) {
		case string:
			mode.subLanguage = subLanguage{set: true, name: v}
		case map[string]any:
			mode.subLanguage = subLanguage{set: true, isList: true, list: decodeStrings(v)}
		}
	case "on:begin":
		mode.onBegin = callbackByName(value)
	case "on:end":
		mode.onEnd = callbackByName(value)
	case "case_insensitive":
		mode.caseInsensitive = value == true
	case "name":
		mode.name, _ = value.(string)
	case "aliases":
		mode.aliases = decodeStrings(value)
	case "disableAutodetect":
		mode.disableAutodetect = value == true
	case "supersetOf":
		mode.supersetOf, _ = value.(string)
	case "classNameAliases":
		mode.classNameAliases, _ = r.ref(value).(map[string]string)
	case "compilerExtensions":
		for _, item := range value.(map[string]any)["arr"].([]any) {
			name, _ := item.(map[string]any)["fn"].(string)
			extension, ok := compilerExtensions[name]
			if !ok {
				panic("hljs: unknown compiler extension " + name)
			}
			mode.compilerExtensions = append(mode.compilerExtensions, extension)
		}
	}
}

var modePropertyKeys = map[string]modeKeys{
	"begin": keyBegin, "end": keyEnd, "match": keyMatch, "illegal": keyIllegal, "lexemes": keyLexemes, "beforeMatch": keyBeforeMatch,
	"className": keyClassName, "contains": keyContains, "variants": keyVariants, "starts": keyStarts,
	"endsParent": keyEndsParent, "endsWithParent": keyEndsWithParent, "excludeBegin": keyExcludeBegin, "excludeEnd": keyExcludeEnd,
	"returnBegin": keyReturnBegin, "returnEnd": keyReturnEnd, "skip": keySkip, "endSameAsBegin": keyEndSameAsBegin,
	"relevance": keyRelevance, "keywords": keyKeywords, "beginKeywords": keyBeginKeywords, "subLanguage": keySubLanguage,
	"on:begin": keyOnBegin, "on:end": keyOnEnd, "case_insensitive": keyCaseInsensitive, "name": keyName, "aliases": keyAliases,
	"disableAutodetect": keyDisableAutodetect, "supersetOf": keySupersetOf, "classNameAliases": keyClassNameAliases,
	"compilerExtensions": keyCompilerExtensions,
}

func decodeKeywordsProperty(object *keywordsObject, key string, value any) {
	if key == "$pattern" {
		object.pattern, object.hasPattern = decodePattern(value), true
		return
	}
	class := keywordClass{name: key}
	switch v := value.(type) {
	case string:
		class.text = v
	case map[string]any:
		class.isList = true
		class.list = decodeStrings(v)
	default:
		panic("hljs: keyword class " + key + " is not a string or an array")
	}
	object.classes = append(object.classes, class)
}

// Text tables from the eager snapshot: RegExp ignoreCase canonicalization and String.prototype.toLowerCase.
var (
	tablesOnce      sync.Once
	canonical       map[rune]rune
	caseClasses     map[rune][]rune
	caseFolded      []rune
	lowerCaseTable  map[rune]string
	systemSymbolSet map[string]bool
)

func loadTables() {
	tablesOnce.Do(func() {
		s := decodeSnapshot(eagerGrammars)
		canonical = make(map[rune]rune, len(s.Canonicalize))
		for _, pair := range s.Canonicalize {
			canonical[rune(pair[0])] = rune(pair[1])
		}
		canon := func(unit rune) rune {
			if c, ok := canonical[unit]; ok {
				return c
			}
			return unit
		}
		members := map[rune][]rune{}
		for unit := range canonical {
			members[canon(unit)] = append(members[canon(unit)], unit)
		}
		caseClasses = map[rune][]rune{}
		for target, units := range members {
			if canon(target) == target {
				units = append(units, target)
			}
			slices.Sort(units)
			if len(units) < 2 {
				continue
			}
			for _, unit := range units {
				caseClasses[unit] = units
				caseFolded = append(caseFolded, unit)
			}
		}
		slices.Sort(caseFolded)
		lowerCaseTable = make(map[rune]string, len(s.LowerCase))
		for _, raw := range s.LowerCase {
			var pair [2]any
			if err := json.Unmarshal(raw, &pair); err != nil {
				panic(fmt.Sprintf("hljs: lowercase table: %v", err))
			}
			lowerCaseTable[rune(pair[0].(float64))] = pair[1].(string)
		}
		systemSymbolSet = make(map[string]bool, len(s.SystemSymbols))
		for _, symbol := range s.SystemSymbols {
			systemSymbolSet[symbol] = true
		}
	})
}

// caseClass lists the code units whose ignoreCase canonical form equals unit's, or nil when unit matches only itself.
func caseClass(unit rune) []rune {
	loadTables()
	return caseClasses[unit]
}

// caseFoldedUnits lists every code unit that matches another under ignoreCase, ascending.
func caseFoldedUnits() []rune {
	loadTables()
	return caseFolded
}

// toLowerCase is String.prototype.toLowerCase over WTF-8. Keywords contain no sigma, so the context-dependent Final_Sigma mapping cannot change a keyword comparison.
func toLowerCase(text string) string {
	ascii := true
	for i := 0; i < len(text); i++ {
		if text[i] >= utf8.RuneSelf {
			ascii = false
			break
		}
	}
	if ascii {
		return strings.ToLower(text)
	}
	loadTables()
	var out strings.Builder
	for len(text) > 0 {
		if len(text) >= 3 && text[0] == 0xed && text[1] >= 0xa0 && text[1] <= 0xbf {
			out.WriteString(text[:3])
			text = text[3:]
			continue
		}
		r, size := utf8.DecodeRuneInString(text)
		if lower, ok := lowerCaseTable[r]; ok && (r != utf8.RuneError || size > 1) {
			out.WriteString(lower)
		} else {
			out.WriteString(text[:size])
		}
		text = text[size:]
	}
	return out.String()
}
