package main

import (
	"fmt"
	"os"
	"slices"
	"strings"
)

const (
	knownGapsBeginPrefix = "<!-- known-gaps:begin"
	knownGapsBegin       = knownGapsBeginPrefix + " generated by `make known-gaps`; do not edit between the markers -->"
	knownGapsEnd         = "<!-- known-gaps:end -->"
)

// dispositionCounts tallies mapping entries by disposition; check and the known-gaps block share it so both report the same totals.
func dispositionCounts(m mapping) map[string]int {
	counts := map[string]int{}
	for _, entry := range m.Entries {
		counts[entry.Disposition]++
	}
	return counts
}

func plural(n int, one, many string) string {
	if n == 1 {
		return one
	}
	return many
}

type knownGapRow struct {
	area, path, status, followUp string
	hot                          bool
}

// renderKnownGaps renders the current-state block from a mapping and policy that validateReleasePolicy already accepted. Open files keep mapping order (sorted by path), hot-path files first.
func renderKnownGaps(inv inventory, m mapping, policy releasePolicy) string {
	counts := dispositionCounts(m)
	entries := make(map[string]policyEntry, len(policy.Entries))
	approved := 0
	approvedByArea := map[string]int{}
	for _, entry := range policy.Entries {
		entries[entry.Path] = entry
		if slices.Contains(entry.Tags, "deferred-0.3.x") {
			approved++
			approvedByArea[entry.Area]++
		}
	}
	var rows []knownGapRow
	for _, entry := range m.Entries {
		if entry.Disposition != "pending" && entry.Disposition != "partial" {
			continue
		}
		reviewed := entries[entry.Path]
		followUp := "none"
		if slices.Contains(reviewed.Tags, "deferred-0.3.x") {
			followUp = "`FOLLOWUP-" + reviewed.Area + "`"
		}
		rows = append(rows, knownGapRow{reviewed.Area, entry.Path, entry.Disposition, followUp, slices.Contains(reviewed.Tags, "hot-path")})
	}
	slices.SortStableFunc(rows, func(a, b knownGapRow) int {
		switch {
		case a.hot && !b.hot:
			return -1
		case !a.hot && b.hot:
			return 1
		}
		return 0
	})
	hot := 0
	for _, r := range rows {
		if r.hot {
			hot++
		}
	}

	var b strings.Builder
	b.WriteString(knownGapsBegin + "\n\n")
	fmt.Fprintf(&b, "Pi %s. `make known-gaps` generates this block from `go run ./test/parity/cmd/testinventorycheck -release-policy`, and `make known-gaps-drift` fails when it is stale. The block names no commit: its totals come from the [reviewed mapping](../../test/parity/interfaces/test-mapping-v%s.json) and the [release policy](../../test/parity/interfaces/test-porting-policy-v%s.json) at the commit that carries this file.\n\n", inv.UpstreamVersion, inv.UpstreamVersion, inv.UpstreamVersion)
	fmt.Fprintf(&b, "The checker reports %d files: %d ported, %d partial, %d scenario-covered, %d designed-out, %d divergence and %d pending. `make test-porting-release` accepts %d approved 0.3.x known %s and reports %d reviewed paths and %d ported (committed baseline %d). %d %s open: %d hot-path and %d without a hot-path tag.\n\n",
		len(inv.Files), counts["ported"], counts["partial"], counts["scenario-covered"], counts["designed-out"], counts["divergence"], counts["pending"],
		approved, plural(approved, "gap", "gaps"), len(policy.Entries), counts["ported"], len(policy.BaselinePorted), len(rows), plural(len(rows), "file is", "files are"), hot, len(rows)-hot)
	if len(rows) == 0 {
		b.WriteString("No test file is open.\n")
	} else {
		b.WriteString("| Area | Upstream test path | Status | Hot path | Follow-up |\n|---|---|---|---|---|\n")
		for _, r := range rows {
			hotPath := "no"
			if r.hot {
				hotPath = "yes"
			}
			fmt.Fprintf(&b, "| %s | `%s` | %s | %s | %s |\n", r.area, r.path, r.status, hotPath, r.followUp)
		}
	}
	parts := make([]string, len(policyAreas))
	for i, area := range policyAreas {
		parts[i] = fmt.Sprintf("%s %d", area, approvedByArea[area])
	}
	b.WriteString("\nApproved known gaps by area: " + strings.Join(parts, ", ") + ". `make test-porting-release` prints the full missing-case text for each approved gap.\n\n")
	b.WriteString(knownGapsEnd)
	return b.String()
}

// spliceKnownGaps replaces the marked block in doc. It fails unless the doc holds exactly one begin marker followed by one end marker.
func spliceKnownGaps(doc, block string) (string, error) {
	begin := strings.Index(doc, knownGapsBeginPrefix)
	end := strings.Index(doc, knownGapsEnd)
	if begin < 0 || end < begin || strings.Count(doc, knownGapsBeginPrefix) != 1 || strings.Count(doc, knownGapsEnd) != 1 {
		return "", fmt.Errorf("known-gaps markers missing or duplicated: need one %q ... %q pair", knownGapsBeginPrefix, knownGapsEnd)
	}
	return doc[:begin] + block + doc[end+len(knownGapsEnd):], nil
}

// syncKnownGaps writes the regenerated block into path, or with check set fails when the committed block differs.
func syncKnownGaps(path, block string, check bool) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	text := strings.ReplaceAll(string(data), "\r\n", "\n")
	updated, err := spliceKnownGaps(text, block)
	if err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	if updated == text {
		if !check && text != string(data) {
			return os.WriteFile(path, []byte(updated), 0o644)
		}
		return nil
	}
	if check {
		return fmt.Errorf("%s: generated known-gaps block is stale (first difference: %s); run `make known-gaps` and commit the result", path, firstDifference(text, updated))
	}
	return os.WriteFile(path, []byte(updated), 0o644)
}

// syncKnownGapsDoc reloads the validated release inputs and writes or checks the requested known-gaps documents.
func syncKnownGapsDoc(inventoryPath, mappingPath, policyPath, write, check string) error {
	if write == "" && check == "" {
		return nil
	}
	var inv inventory
	var m mapping
	var policy releasePolicy
	if err := decodeJSON(inventoryPath, &inv); err != nil {
		return err
	}
	if err := decodeJSON(mappingPath, &m); err != nil {
		return err
	}
	if err := decodeJSON(policyPath, &policy); err != nil {
		return err
	}
	block := renderKnownGaps(inv, m, policy)
	if write != "" {
		if err := syncKnownGaps(write, block, false); err != nil {
			return err
		}
	}
	if check != "" {
		return syncKnownGaps(check, block, true)
	}
	return nil
}

// firstDifference names the first line at which the committed and generated documents differ.
func firstDifference(committed, generated string) string {
	have, want := strings.Split(committed, "\n"), strings.Split(generated, "\n")
	for i := range max(len(have), len(want)) {
		var h, w string
		if i < len(have) {
			h = have[i]
		}
		if i < len(want) {
			w = want[i]
		}
		if h != w {
			return fmt.Sprintf("line %d, committed %q, generated %q", i+1, h, w)
		}
	}
	return "none"
}
