// Code generated by go generate ./coding/extension/host/subprocess; DO NOT EDIT.

package subprocess

const nodeRuntimeHash = "\x1b?\xc8~+\xbbG\xd5%\xec17=\xc5\xeaN\xde\\];\xe4i\x8dW\xf3K\xe9[\x8dN#\xcc"
