// Code generated by go generate ./coding/extension/host/subprocess; DO NOT EDIT.

package subprocess

const nodeRuntimeHash = "\xe4\xfe\x8e\x01ț\xb2\xb5!\xcb\xfa\xe9\x91\x13]=\xe3\x1f\xccpU\xe1\x9d,\xb4\x93\nA\x88?\xa0~"
