// Code generated by go generate ./coding/extension/host/subprocess; DO NOT EDIT.

package subprocess

const nodeRuntimeHash = "\x97,h9\xe2\xb8\xc6 \x0e\x95\xad\xe1\vRѤ\x85\x81\xea\xfa\xec\x197h3|\x86=\x03\xb4\xe5b"
