import { spawnSync } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import ts from "typescript";

// gen-go-stubs turns one upstream package's public TypeScript API into a
// compiling Go skeleton for a porter: one *_stub.go file per upstream source
// file with Pi's exported names, doc comments citing upstream file:line, and
// bodies that panic with "unported: <upstream symbol>"; one
// *_upstream_test.go skeleton per upstream test file with a Go subtest per
// it()/test() case; and the test-mapping rows those files support.
//
// The generator owns only files that start with its header and whose recorded
// body hash still matches. It never writes over any other file. Symbols that a
// hand-written Go file in the target directory already declares are omitted,
// and upstream cases that a hand-written Go test cites with an
// `upstream: <test path>:<line>` marker are treated as ported, so re-running
// it after porting shrinks the stubs and flips the ledger rows.

export const HEADER_PREFIX = "// Code generated by gen-go-stubs";
const HASH_PREFIX = "// stubgen:sha256=";

const GO_KEYWORDS = new Set([
  "break", "case", "chan", "const", "continue", "default", "defer", "else", "fallthrough", "for", "func", "go", "goto",
  "if", "import", "interface", "map", "package", "range", "return", "select", "struct", "switch", "type", "var",
  // Predeclared identifiers that would shadow types used by the stubs.
  "any", "error", "string", "bool", "byte", "len", "cap", "new", "make", "copy", "close", "delete", "panic", "append",
  // Packages the stubs import.
  "context", "big", "time", "ctx",
]);

// goName maps an upstream identifier to its exported Go spelling. Pi's
// spelling is kept (Id stays Id); SCREAMING_SNAKE constants become PascalCase
// words (PROTOCOL_VERSION → ProtocolVersion), as the existing ports do.
export function goName(name) {
  const bare = name.replace(/^[#_$]+/, "");
  if (/^[A-Z0-9_]+$/.test(bare) && bare.includes("_")) {
    return bare.split("_").filter(Boolean).map((word) => word[0] + word.slice(1).toLowerCase()).join("");
  }
  if (bare === "") return "X";
  const out = bare[0].toUpperCase() + bare.slice(1);
  return out.replace(/[^A-Za-z0-9_]/g, "_");
}

function paramName(name, index) {
  let out = name.replace(/[^A-Za-z0-9_]/g, "");
  if (!out) out = `arg${index}`;
  if (/^[0-9]/.test(out)) out = `arg${out}`;
  if (GO_KEYWORDS.has(out)) out = `${out}Value`;
  return out;
}

function sha256(text) {
  return crypto.createHash("sha256").update(text).digest("hex");
}

function normalizePath(value) {
  return value.split(path.sep).join("/");
}

// ── Upstream entry points ───────────────────────────────────────────────────

// packageEntries returns the source files behind the package's public
// subpath exports: the explicit `source` condition when present, otherwise the
// dist type file mapped back to src/*.ts.
export function packageEntries(packageDir) {
  const manifest = JSON.parse(fs.readFileSync(path.join(packageDir, "package.json"), "utf8"));
  const entries = [];
  const add = (subpath, relative) => {
    if (!relative) return;
    let source = relative.replace(/^\.\//, "");
    if (!source.endsWith(".ts") || source.endsWith(".d.ts")) {
      source = source.replace(/^dist\//, "src/").replace(/\.d\.ts$|\.js$/, ".ts");
    }
    const absolute = path.join(packageDir, source);
    if (fs.existsSync(absolute)) entries.push({ subpath, file: absolute });
  };
  const exportsField = manifest.exports;
  if (exportsField && typeof exportsField === "object") {
    for (const [subpath, target] of Object.entries(exportsField)) {
      if (subpath.endsWith("package.json")) continue;
      if (typeof target === "string") add(subpath, target);
      else add(subpath, target.source ?? target.types ?? target.import ?? target.default);
    }
  }
  if (entries.length === 0) {
    for (const candidate of [manifest.types, manifest.main, "src/index.ts"]) {
      add(".", candidate);
      if (entries.length) break;
    }
  }
  return entries;
}

function workspacePaths(sourceRoot) {
  const paths = {};
  const packagesDir = path.join(sourceRoot, "packages");
  for (const name of fs.readdirSync(packagesDir)) {
    const manifestPath = path.join(packagesDir, name, "package.json");
    if (!fs.existsSync(manifestPath)) continue;
    const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
    if (!manifest.name) continue;
    for (const entry of packageEntries(path.join(packagesDir, name))) {
      const spec = entry.subpath === "." ? manifest.name : `${manifest.name}/${entry.subpath.replace(/^\.\//, "")}`;
      paths[spec] = [entry.file];
    }
  }
  return paths;
}

// ── Go type rendering ───────────────────────────────────────────────────────

class Renderer {
  constructor(checker, owned, imports, typeIndex = new Map()) {
    this.checker = checker;
    this.owned = owned; // TS symbol → { goName, kind }
    this.imports = imports;
    this.typeIndex = typeIndex; // interned TS type → owned alias (TypeBox Static<> results)
    this.rendering = undefined;
    this.foreign = undefined;
    this.typeParams = new Set();
  }

  ownedName(symbol) {
    if (!symbol) return undefined;
    let resolved = symbol;
    if (resolved.flags & ts.SymbolFlags.Alias) resolved = this.checker.getAliasedSymbol(resolved);
    return this.owned.get(resolved);
  }

  // type renders a Go type for a TypeScript type. Unknown and foreign shapes
  // become `any`; the doc comment keeps the upstream spelling.
  type(type, depth = 0) {
    const checker = this.checker;
    if (depth > 6) return "any";
    const f = type.flags;
    if (f & (ts.TypeFlags.Any | ts.TypeFlags.Unknown | ts.TypeFlags.Never)) return "any";
    if (f & ts.TypeFlags.TypeParameter) {
      // Only the declaration's own type parameters are in Go scope; a generic
      // method's or callback's parameters (Go has none) erase to any.
      const name = goName(type.symbol?.name ?? "T");
      return this.typeParams.has(name) ? name : "any";
    }
    const indexed = this.typeIndex.get(type);
    if (indexed && indexed !== this.rendering) return this.reference(indexed, undefined, depth);
    const foreignIndexed = this.foreign?.typeIndex.get(type);
    if (foreignIndexed) return this.foreignReference(foreignIndexed);
    if (type.aliasSymbol) {
      const foreignAlias = this.foreignName(type.aliasSymbol, type.aliasTypeArguments, depth);
      if (foreignAlias) return foreignAlias;
      const owned = this.ownedName(type.aliasSymbol);
      if (owned && owned.kind !== "value") return this.reference(owned, type.aliasTypeArguments, depth);
    }
    if (f & (ts.TypeFlags.String | ts.TypeFlags.StringLiteral | ts.TypeFlags.TemplateLiteral)) return "string";
    if (f & (ts.TypeFlags.Number | ts.TypeFlags.NumberLiteral)) return "float64";
    if (f & (ts.TypeFlags.Boolean | ts.TypeFlags.BooleanLiteral)) return "bool";
    if (f & (ts.TypeFlags.BigInt | ts.TypeFlags.BigIntLiteral)) {
      this.imports.add("math/big");
      return "*big.Int";
    }
    if (f & (ts.TypeFlags.Void | ts.TypeFlags.Undefined | ts.TypeFlags.Null)) return "struct{}";
    if (f & ts.TypeFlags.ESSymbol || f & ts.TypeFlags.UniqueESSymbol) return "any";
    if (isTupleLike(checker, type)) return "[]any";
    if (type.isUnion()) return this.union(type, depth);
    if (type.isIntersection()) return "any";
    const symbol = type.getSymbol();
    const name = symbol?.name;
    if (name === "Uint8Array" || name === "ArrayBuffer" || name === "Buffer") return "[]byte";
    if (name === "Promise" || name === "PromiseLike") {
      const [inner] = checker.getTypeArguments(type);
      return inner ? this.type(inner, depth + 1) : "any";
    }
    if (checker.isArrayType(type) || name === "ReadonlyArray") {
      const [element] = checker.getTypeArguments(type);
      return `[]${element ? this.elem(element, depth) : "any"}`;
    }
    if (checker.isTupleType(type)) return "[]any";
    if (name === "Map" || name === "ReadonlyMap") {
      const [key, value] = checker.getTypeArguments(type);
      return `map[${this.mapKey(key, depth)}]${value ? this.elem(value, depth) : "any"}`;
    }
    if (name === "Set" || name === "ReadonlySet") {
      const [key] = checker.getTypeArguments(type);
      return `map[${this.mapKey(key, depth)}]struct{}`;
    }
    if (name === "Error" || name === "TypeError" || name === "RangeError") return "error";
    if (name === "Date") {
      this.imports.add("time");
      return "time.Time";
    }
    if (name === "AbortSignal") {
      this.imports.add("context");
      return "context.Context";
    }
    const foreignNamed = this.foreignName(symbol, f & ts.TypeFlags.Object && type.objectFlags & ts.ObjectFlags.Reference ? checker.getTypeArguments(type) : undefined, depth);
    if (foreignNamed) return foreignNamed;
    const owned = this.ownedName(symbol);
    if (owned && owned.kind !== "value") {
      const args = f & ts.TypeFlags.Object && type.objectFlags & ts.ObjectFlags.Reference ? checker.getTypeArguments(type) : undefined;
      return this.reference(owned, args, depth);
    }
    const signatures = type.getCallSignatures();
    if (signatures.length > 0 && type.getProperties().length === 0) return this.funcType(signatures[0], depth);
    const indexType = type.getStringIndexType?.();
    if (indexType && type.getProperties().length === 0) return `map[string]${this.elem(indexType, depth)}`;
    return "any";
  }

  // foreignName renders a symbol exported by another workspace package that
  // the caller mapped to a Go import path (--import); others stay `any`.
  foreignName(symbol, args, depth = 0) {
    if (!symbol || !this.foreign) return undefined;
    let resolved = symbol;
    if (resolved.flags & ts.SymbolFlags.Alias) resolved = this.checker.getAliasedSymbol(resolved);
    const entry = this.foreign.symbols.get(resolved);
    return entry ? this.foreignReference(entry, args, depth) : undefined;
  }

  foreignReference(entry, args, depth = 0) {
    this.imports.add(entry.importPath);
    const typeArgs = entry.typeParameterCount > 0
      ? `[${Array.from({ length: entry.typeParameterCount }, (_, i) => (args?.[i] ? this.type(args[i], depth + 1) : "any")).join(", ")}]`
      : "";
    return `${entry.kind === "class" ? "*" : ""}${entry.alias}.${entry.goName}${typeArgs}`;
  }

  reference(owned, args, depth) {
    const typeArgs = owned.typeParameterCount > 0
      ? `[${Array.from({ length: owned.typeParameterCount }, (_, i) => (args?.[i] ? this.type(args[i], depth + 1) : "any")).join(", ")}]`
      : "";
    return `${owned.kind === "class" ? "*" : ""}${owned.goName}${typeArgs}`;
  }

  elem(type, depth) {
    return this.type(type, depth + 1);
  }

  mapKey(type, depth) {
    if (!type) return "string";
    const rendered = this.type(type, depth + 1);
    return ["string", "float64", "bool"].includes(rendered) || /^\*?[A-Z]/.test(rendered) ? rendered : "string";
  }

  union(type, depth) {
    const present = type.types.filter((member) => !(member.flags & (ts.TypeFlags.Undefined | ts.TypeFlags.Null | ts.TypeFlags.Void)));
    const nullable = present.length !== type.types.length;
    if (present.length === 0) return "struct{}";
    if (present.every((member) => member.flags & ts.TypeFlags.BooleanLike)) return nullable ? "*bool" : "bool";
    if (present.every((member) => member.flags & ts.TypeFlags.StringLike)) return nullable ? "*string" : "string";
    if (present.every((member) => member.flags & ts.TypeFlags.NumberLike)) return nullable ? "*float64" : "float64";
    if (present.length === 1) {
      const inner = this.type(present[0], depth + 1);
      return nullable ? pointerTo(inner) : inner;
    }
    // Promise-or-value returns (`T | Promise<T>`) collapse to T.
    const unwrapped = present.map((member) => (member.getSymbol()?.name === "Promise" ? this.checker.getTypeArguments(member)[0] : member));
    const rendered = new Set(unwrapped.map((member) => (member ? this.type(member, depth + 1) : "any")));
    if (rendered.size === 1) {
      const inner = [...rendered][0];
      return nullable ? pointerTo(inner) : inner;
    }
    return "any";
  }

  // funcType renders a callback; a Promise result becomes an error result too.
  funcType(signature, depth) {
    const { params, results } = this.signature(signature, { depth: depth + 1, withContext: false });
    return `func(${params.map((param) => param.type).join(", ")})${formatResults(results)}`;
  }

  // signature renders Go parameters and results. Async and throwing upstream
  // functions return an error; async functions also take a context first.
  signature(signature, { depth = 0, withContext = false, throws = false } = {}) {
    const checker = this.checker;
    const params = [];
    let async = false;
    const returnType = checker.getReturnTypeOfSignature(signature);
    if (isPromise(returnType) || (returnType.isUnion() && returnType.types.some(isPromise))) async = true;
    if (async && withContext) {
      this.imports.add("context");
      params.push({ name: "ctx", type: "context.Context" });
    }
    signature.getParameters().forEach((parameter, index) => {
      const declaration = parameter.valueDeclaration ?? parameter.declarations?.[0];
      let paramType = checker.getTypeOfSymbolAtLocation(parameter, declaration ?? parameter.declarations?.[0]);
      const rest = declaration && ts.isParameter(declaration) && declaration.dotDotDotToken;
      if (paramType.symbol?.name === "AbortSignal" || (paramType.isUnion?.() && paramType.types.some((t) => t.symbol?.name === "AbortSignal"))) {
        if (!withContext || !async) {
          this.imports.add("context");
          params.push({ name: "ctx", type: "context.Context" });
        }
        return;
      }
      if (rest && checker.isArrayType(paramType)) {
        const [element] = checker.getTypeArguments(paramType);
        params.push({ name: paramName(parameter.name, index), type: `...${element ? this.type(element, depth + 1) : "any"}` });
        return;
      }
      let rendered = this.type(paramType, depth + 1);
      const optional = declaration && ts.isParameter(declaration) && (declaration.questionToken || declaration.initializer);
      // An omitted options object is the zero value of a struct whose fields are all optional.
      if (optional && isScalar(rendered)) rendered = pointerTo(rendered);
      params.push({ name: paramName(parameter.name, index), type: rendered });
    });
    const results = [];
    const predicate = checker.getTypePredicateOfSignature(signature);
    if (predicate) results.push("bool");
    else {
      const inner = async && isPromise(returnType) ? checker.getTypeArguments(returnType)[0] ?? returnType : returnType;
      if (!(inner.flags & (ts.TypeFlags.Void | ts.TypeFlags.Undefined | ts.TypeFlags.Never))) {
        const rendered = this.type(inner, depth + 1);
        if (rendered !== "struct{}" && rendered !== "*struct{}") results.push(rendered);
      }
    }
    if (async || throws) results.push("error");
    return { params: dedupeParams(params), results, async };
  }
}

// isTupleLike reports a tuple, or a union whose every member is a tuple or
// array (Pi's operation vocabularies); Go carries them as []any.
function isTupleLike(checker, type) {
  if (checker.isTupleType(type)) return true;
  if (!type.isUnion()) return false;
  const present = type.types.filter((member) => !(member.flags & (ts.TypeFlags.Undefined | ts.TypeFlags.Null)));
  return present.length > 1 && present.every((member) => checker.isTupleType(member) || checker.isArrayType(member)) && present.some((member) => checker.isTupleType(member));
}

function validField(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) && !name.startsWith("__@");
}

function dedupeParams(params) {
  const seen = new Map();
  return params.map((param) => {
    const count = seen.get(param.name) ?? 0;
    seen.set(param.name, count + 1);
    return count === 0 ? param : { ...param, name: `${param.name}${count + 1}` };
  });
}

function isPromise(type) {
  const name = type.getSymbol()?.name;
  return name === "Promise" || name === "PromiseLike";
}

function isScalar(rendered) {
  return ["string", "float64", "bool"].includes(rendered) || /^[A-Z][A-Za-z0-9_]*$/.test(rendered);
}

// Go names whose types already have a nil value (func, interface, map, slice
// aliases); an optional reference to one is not wrapped in a pointer.
const nilableNames = new Set();
// Structs whose every field is optional; their zero value is the omitted object.
const optionalStructNames = new Set();
// Variants of a sealed union: the Go type is the discriminant, so their
// single-string-literal properties (`type: "hello"`) are not fields.
const sealedMemberNames = new Set();

function pointerTo(rendered) {
  const base = rendered.replace(/\[.*\]$/, "");
  if (rendered === "struct{}" || nilableNames.has(base) || optionalStructNames.has(base)) return rendered;
  if (rendered.startsWith("*") || rendered.startsWith("[]") || rendered.startsWith("map[") || rendered.startsWith("func(") || rendered === "any" || rendered === "error" || rendered.startsWith("context.")) return rendered;
  return `*${rendered}`;
}

function formatResults(results) {
  if (results.length === 0) return "";
  if (results.length === 1) return ` ${results[0]}`;
  return ` (${results.join(", ")})`;
}

function zeroReturn() {
  return "";
}

// ── Declarations ────────────────────────────────────────────────────────────

function docLines(node, source, upstreamLabel) {
  const lines = [];
  const jsDoc = ts.getJSDocCommentsAndTags(node).filter(ts.isJSDoc);
  for (const doc of jsDoc) {
    const text = typeof doc.comment === "string" ? doc.comment : ts.getTextOfJSDocComment(doc.comment) ?? "";
    for (const line of text.split("\n")) if (line.trim()) lines.push(line.trim());
  }
  lines.push(`Ports ${upstreamLabel}.`);
  return lines;
}

function lineOf(node) {
  const source = node.getSourceFile();
  return source.getLineAndCharacterOfPosition(node.getStart(source)).line + 1;
}

function containsThrow(node) {
  let found = false;
  const visit = (child) => {
    if (found) return;
    if (ts.isThrowStatement(child)) {
      found = true;
      return;
    }
    // A nested function's throw belongs to that function.
    if (child !== node && (ts.isFunctionLike(child) || ts.isClassLike(child))) return;
    ts.forEachChild(child, visit);
  };
  visit(node);
  return found;
}

// throwingDeclarations is the fixpoint of package functions that can throw to
// their caller: a throw statement in the body, or an unguarded call (or `new`)
// to a package function that throws. Their Go ports return an error.
function throwingDeclarations(program, checker, packageDir) {
  const functions = [];
  for (const source of program.getSourceFiles()) {
    if (source.isDeclarationFile || !source.fileName.startsWith(packageDir + path.sep)) continue;
    const visit = (node) => {
      if ((ts.isFunctionLike(node) && node.body) || ts.isConstructorDeclaration(node)) functions.push(node);
      ts.forEachChild(node, visit);
    };
    visit(source);
  }
  const throwing = new Set(functions.filter((node) => containsThrow(node)));
  const calleeOf = (call) => {
    const signature = checker.getResolvedSignature(call);
    let declaration = signature?.declaration;
    if (declaration && ts.isNewExpression(call) && ts.isClassDeclaration(declaration)) declaration = declaration.members.find(ts.isConstructorDeclaration);
    return declaration;
  };
  for (let changed = true; changed;) {
    changed = false;
    for (const node of functions) {
      if (throwing.has(node)) continue;
      let found = false;
      const visit = (child, guarded) => {
        if (found) return;
        if (child !== node && (ts.isFunctionLike(child) || ts.isClassLike(child))) return;
        if (ts.isTryStatement(child)) {
          visit(child.tryBlock, true);
          if (child.catchClause) visit(child.catchClause, guarded);
          if (child.finallyBlock) visit(child.finallyBlock, guarded);
          return;
        }
        if (!guarded && (ts.isCallExpression(child) || ts.isNewExpression(child))) {
          const callee = calleeOf(child);
          if (callee && throwing.has(callee)) {
            found = true;
            return;
          }
        }
        ts.forEachChild(child, (grandchild) => visit(grandchild, guarded));
      };
      visit(node, false);
      if (found) {
        throwing.add(node);
        changed = true;
      }
    }
  }
  return throwing;
}

// trivialErrorConstructor reports an Error subclass constructor that only
// forwards its required parameters or a literal message to super() and same-named fields and
// sets `name`; a Go composite literal (&CborError{Message: m}) is its port.
function trivialErrorConstructor(ctor) {
  if (!ctor?.body) return true;
  if (ctor.parameters.some((parameter) => parameter.initializer || parameter.questionToken)) return false;
  const params = new Set(ctor.parameters.map((parameter) => parameter.name.getText()));
  return ctor.body.statements.every((statement) => {
    if (!ts.isExpressionStatement(statement)) return false;
    const expression = statement.expression;
    if (ts.isCallExpression(expression) && expression.expression.kind === ts.SyntaxKind.SuperKeyword) {
      return expression.arguments.every((argument) => (ts.isIdentifier(argument) && params.has(argument.text)) || ts.isStringLiteralLike(argument));
    }
    if (ts.isBinaryExpression(expression) && expression.operatorToken.kind === ts.SyntaxKind.EqualsToken && ts.isPropertyAccessExpression(expression.left) && expression.left.expression.kind === ts.SyntaxKind.ThisKeyword) {
      const field = expression.left.name.text;
      return field === "name" ? ts.isStringLiteral(expression.right) : ts.isIdentifier(expression.right) && params.has(expression.right.text);
    }
    return false;
  });
}

function isErrorClass(checker, declaration) {
  let type = checker.getTypeAtLocation(declaration);
  for (let depth = 0; depth < 8 && type; depth++) {
    if (type.symbol?.name === "Error") return true;
    const bases = type.getBaseTypes?.() ?? [];
    type = bases[0];
  }
  return false;
}

function typeParameterList(renderer, declaration) {
  const parameters = declaration.typeParameters ?? [];
  renderer.typeParams = new Set(parameters.map((parameter) => goName(parameter.name.text)));
  if (parameters.length === 0) return "";
  return `[${parameters.map((parameter) => `${goName(parameter.name.text)} any`).join(", ")}]`;
}

function typeParameterUse(declaration) {
  const parameters = declaration.typeParameters ?? [];
  if (parameters.length === 0) return "";
  return `[${parameters.map((parameter) => goName(parameter.name.text)).join(", ")}]`;
}

function goConstExpression(node, constNames) {
  if (!node) return undefined;
  let expression = node;
  while (ts.isAsExpression(expression) || ts.isParenthesizedExpression(expression) || ts.isSatisfiesExpression?.(expression)) {
    if (ts.isParenthesizedExpression(expression)) {
      const inner = goConstExpression(expression.expression, constNames);
      return inner === undefined ? undefined : `(${inner})`;
    }
    expression = expression.expression;
  }
  if (ts.isNumericLiteral(expression)) return expression.getText();
  if (ts.isStringLiteral(expression) || ts.isNoSubstitutionTemplateLiteral(expression)) return JSON.stringify(expression.text);
  if (expression.kind === ts.SyntaxKind.TrueKeyword) return "true";
  if (expression.kind === ts.SyntaxKind.FalseKeyword) return "false";
  if (ts.isPrefixUnaryExpression(expression) && expression.operator === ts.SyntaxKind.MinusToken) {
    const inner = goConstExpression(expression.operand, constNames);
    return inner === undefined ? undefined : `-${inner}`;
  }
  if (ts.isBinaryExpression(expression)) {
    const operator = expression.operatorToken.getText();
    if (!["+", "-", "*", "/", "<<", "|", "&"].includes(operator)) return undefined;
    const left = goConstExpression(expression.left, constNames);
    const right = goConstExpression(expression.right, constNames);
    return left === undefined || right === undefined ? undefined : `${left} ${operator} ${right}`;
  }
  if (ts.isIdentifier(expression) && constNames.has(expression.text)) return constNames.get(expression.text);
  return undefined;
}

// collectExports resolves the public API: every symbol reachable from the
// package's export entry points, with its declaration and owning source file.
function collectExports(program, checker, entries) {
  const found = new Map();
  for (const entry of entries) {
    const source = program.getSourceFile(entry.file);
    if (!source) continue;
    const moduleSymbol = checker.getSymbolAtLocation(source);
    if (!moduleSymbol) continue;
    for (const exported of checker.getExportsOfModule(moduleSymbol)) {
      let symbol = exported;
      if (symbol.flags & ts.SymbolFlags.Alias) symbol = checker.getAliasedSymbol(symbol);
      if (found.has(symbol)) continue;
      const declarations = (symbol.declarations ?? []).filter((declaration) => !declaration.getSourceFile().isDeclarationFile);
      if (declarations.length === 0) continue;
      found.set(symbol, { name: exported.name, symbol, declarations, subpath: entry.subpath });
    }
  }
  return [...found.values()];
}

// foreignPackageEntries resolves --import mappings (npm name → Go import
// path) to the mapped workspace packages' entry points.
function foreignPackageEntries(sourceRoot, imports) {
  const out = [];
  const packagesDir = path.join(sourceRoot, "packages");
  for (const name of fs.readdirSync(packagesDir)) {
    const manifestPath = path.join(packagesDir, name, "package.json");
    if (!fs.existsSync(manifestPath)) continue;
    const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
    const importPath = imports[manifest.name];
    if (!importPath) continue;
    out.push({ name: manifest.name, importPath, alias: importPath.split("/").pop().replace(/[^A-Za-z0-9_]/g, ""), entries: packageEntries(path.join(packagesDir, name)) });
  }
  return out;
}

function indexForeignPackages(program, checker, foreignPackages) {
  const symbols = new Map();
  const typeIndex = new Map();
  for (const foreignPackage of foreignPackages) {
    for (const item of collectExports(program, checker, foreignPackage.entries)) {
      const declaration = item.declarations.find((d) => ts.isInterfaceDeclaration(d) || ts.isTypeAliasDeclaration(d) || ts.isClassDeclaration(d) || ts.isEnumDeclaration(d));
      if (!declaration) continue;
      const entry = { goName: goName(item.name), kind: ts.isClassDeclaration(declaration) ? "class" : "type", importPath: foreignPackage.importPath, alias: foreignPackage.alias, typeParameterCount: declaration.typeParameters?.length ?? 0 };
      symbols.set(item.symbol, entry);
      const type = checker.getTypeAtLocation(declaration);
      if (!declaration.typeParameters?.length && (type.flags & (ts.TypeFlags.Object | ts.TypeFlags.Intersection) || (type.isUnion() && !(type.flags & ts.TypeFlags.Boolean))) && !typeIndex.has(type)) typeIndex.set(type, entry);
    }
  }
  return { symbols, typeIndex };
}

// ── Existing Go code ────────────────────────────────────────────────────────

export function readHeader(text) {
  if (!text.startsWith(HEADER_PREFIX)) return undefined;
  const lines = text.split("\n");
  const hashLine = lines[1] ?? "";
  if (!hashLine.startsWith(HASH_PREFIX)) return { valid: false };
  const recorded = hashLine.slice(HASH_PREFIX.length).trim();
  const body = lines.slice(2).join("\n");
  return { valid: recorded === sha256(body) };
}

function gofmt(body) {
  const result = spawnSync("gofmt", [], { input: body, encoding: "utf8" });
  if (result.status !== 0) throw new Error(`gofmt rejected generated Go:\n${result.stderr}\n${body}`);
  return result.stdout;
}

function withHeader(label, rawBody) {
  const body = `\n${gofmt(rawBody)}`;
  return `${HEADER_PREFIX} from ${label}; DO NOT EDIT.\n${HASH_PREFIX}${sha256(body)}\n${body}`;
}

// scanGoPackage lists the top-level identifiers, methods, and struct fields
// (`Type.Field`, including embedded types) declared by the hand-written
// (non-generated) Go files of a directory, and the public subpaths their
// `stubgen:subpath <subpath>` markers delegate to another Go package.
export function scanGoPackage(dir) {
  const declared = new Set();
  const methods = new Set();
  const fields = new Set();
  const structs = new Set();
  const delegatedSubpaths = new Set();
  const testFiles = [];
  if (!fs.existsSync(dir)) return { declared, methods, fields, structs, delegatedSubpaths, testFiles, packageName: undefined };
  let packageName;
  for (const name of fs.readdirSync(dir).sort()) {
    if (!name.endsWith(".go")) continue;
    const text = fs.readFileSync(path.join(dir, name), "utf8");
    if (readHeader(text)) continue;
    if (name.endsWith("_test.go")) {
      testFiles.push({ name, text });
      continue;
    }
    // `stubgen:omit <GoName>` records a deliberate Go-mechanics omission.
    for (const match of text.matchAll(/stubgen:omit\s+([A-Za-z_][A-Za-z0-9_.]*)/g)) {
      if (match[1].includes(".")) methods.add(match[1]);
      else declared.add(match[1]);
    }
    for (const match of text.matchAll(/stubgen:subpath\s+(\.[^\s]*)/g)) delegatedSubpaths.add(match[1]);
    const packageMatch = /^package\s+(\w+)/m.exec(text);
    if (packageMatch && !packageName) packageName = packageMatch[1];
    let block;
    let struct; // { name, indent } while inside a multi-line struct body
    const addFields = (owner, body) => {
      for (const raw of body.split(/;|\n/)) {
        const field = raw.replace(/\/\/.*$/, "").replace(/`[^`]*`/, "").trim();
        if (!field || field.startsWith("}")) continue;
        const embedded = /^\*?(?:[A-Za-z_]\w*\.)?([A-Za-z_]\w*)(?:\[.*\])?$/.exec(field);
        if (embedded) {
          fields.add(`${owner}.${embedded[1]}`);
          continue;
        }
        const named = /^([A-Za-z_]\w*(?:\s*,\s*[A-Za-z_]\w*)*)\s+\S/.exec(field);
        if (named) for (const ident of named[1].split(",")) fields.add(`${owner}.${ident.trim()}`);
      }
    };
    for (const line of text.split("\n")) {
      if (struct) {
        if (line.startsWith(`${struct.indent}}`)) struct = undefined;
        else if (line.startsWith(`${struct.indent}\t`) && !line.startsWith(`${struct.indent}\t\t`)) addFields(struct.name, line);
        continue;
      }
      const structHead = /^(\t?)(?:type\s+)?([A-Za-z_]\w*)(?:\[[^\]]*\])?\s+struct\s*\{(.*)$/.exec(line);
      if (structHead && (structHead[1] === "" ? /^type\s/.test(line) : block === "type")) {
        const rest = structHead[3];
        if (rest.trimEnd().endsWith("}")) addFields(structHead[2], rest.trimEnd().slice(0, -1));
        else struct = { name: structHead[2], indent: structHead[1] };
      }
      if (block) {
        if (/^\)/.test(line)) {
          block = undefined;
          continue;
        }
        const match = /^\t([A-Za-z_][A-Za-z0-9_]*(?:\s*,\s*[A-Za-z_][A-Za-z0-9_]*)*)/.exec(line);
        if (match) for (const ident of match[1].split(",")) {
          declared.add(ident.trim());
          if (block === "type" && /^\t\w+(\[[^\]]*\])?\s+struct\b/.test(line)) structs.add(ident.trim());
        }
        continue;
      }
      let match = /^(const|var|type)\s+\($/.exec(line);
      if (match) {
        block = match[1];
        continue;
      }
      match = /^func\s+\(\s*\w*\s*\*?\s*([A-Za-z_]\w*)(?:\[[^\]]*\])?\s*\)\s*([A-Za-z_]\w*)/.exec(line);
      if (match) {
        methods.add(`${match[1]}.${match[2]}`);
        continue;
      }
      match = /^func\s+([A-Za-z_]\w*)/.exec(line);
      if (match) {
        declared.add(match[1]);
        continue;
      }
      match = /^type\s+([A-Za-z_]\w*)(\[[^\]]*\])?\s+(\S+)/.exec(line);
      if (match) {
        declared.add(match[1]);
        if (match[3].startsWith("struct")) structs.add(match[1]);
        continue;
      }
      match = /^(?:const|var)\s+([A-Za-z_]\w*(?:\s*,\s*[A-Za-z_]\w*)*)/.exec(line);
      if (match) for (const ident of match[1].split(",")) declared.add(ident.trim());
    }
  }
  return { declared, methods, fields, structs, delegatedSubpaths, testFiles, packageName };
}

// portedCases reads `upstream: <path>:<line>` markers in hand-written Go
// tests. A marker counts unless the code that follows it, up to the next
// marker, still skips as unported. It also records the enclosing Test function.
export function portedCases(testFiles, relativeDir) {
  const ported = new Map();
  const marker = /(packages\/[^\s:]+\.test\.ts):(\d+)/g;
  for (const file of testFiles) {
    const text = file.text;
    const positions = [];
    for (const match of text.matchAll(marker)) positions.push({ index: match.index, key: `${match[1]}:${match[2]}` });
    positions.forEach((position, index) => {
      const end = index + 1 < positions.length ? positions[index + 1].index : text.length;
      if (text.slice(position.index, end).includes('t.Skip("unported')) return;
      const before = text.slice(0, position.index);
      const functions = [...before.matchAll(/^func\s+(Test\w+)\s*\(/gm)];
      const testName = functions.length ? functions[functions.length - 1][1] : undefined;
      const evidence = `${relativeDir}/${file.name}${testName ? `#${testName}` : ""}`;
      if (!ported.has(position.key)) ported.set(position.key, new Set());
      ported.get(position.key).add(evidence);
    });
  }
  return ported;
}

// ── Generation ──────────────────────────────────────────────────────────────

function goFileBase(relativeSource) {
  return relativeSource
    .replace(/^src\//, "")
    .replace(/\.tsx?$/, "")
    .replace(/[/.-]/g, "_")
    .replace(/[^A-Za-z0-9_]/g, "")
    .toLowerCase();
}

function upstreamLabel(packageRelative, declaration, name) {
  return `${packageRelative}:${lineOf(declaration)} (${name})`;
}

// createHost resolves workspace packages to their sources and third-party
// imports (typebox, ...) through the given node_modules roots, so TypeBox
// Static<> aliases and other library-derived shapes keep their real types.
function createHost(options, dependencyRoots) {
  const host = ts.createCompilerHost(options);
  host.resolveModuleNames = (moduleNames, containingFile) => moduleNames.map((name) => {
    const direct = ts.resolveModuleName(name, containingFile, options, host).resolvedModule;
    if (direct) return direct;
    for (const root of dependencyRoots) {
      const resolved = ts.resolveModuleName(name, path.join(root, "__stubgen__.ts"), options, host).resolvedModule;
      if (resolved) return resolved;
    }
    return undefined;
  });
  return host;
}

// defaultDependencyRoots finds the locked Pi package installation, whose
// nested node_modules carries the exact third-party versions Pi pins.
export function defaultDependencyRoots(repoRoot) {
  const roots = [];
  for (const candidate of [
    "extensions/sdk-ts/node_modules/@earendil-works/pi-coding-agent/node_modules",
    "extensions/sdk-ts/node_modules",
    "test/parity/interface-extractor/node_modules",
  ]) {
    const absolute = path.join(repoRoot, candidate);
    if (fs.existsSync(absolute)) roots.push(absolute);
  }
  return roots;
}

// moduleEntries lists every non-declaration source file of the package, so
// `scope: "module"` also stubs exports that the public entry points do not
// re-export (internal modules a port still needs, such as truncate.ts).
function moduleEntries(packageDir) {
  const out = [];
  const visit = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) visit(full);
      else if (/\.tsx?$/.test(entry.name) && !entry.name.endsWith(".d.ts")) out.push({ subpath: normalizePath(path.relative(packageDir, full)), file: full });
    }
  };
  visit(path.join(packageDir, "src"));
  return out;
}

// subpaths restricts the run to those public subpaths (for a subpath ported
// into its own Go package); without it, subpaths that a hand-written file in
// outDir delegates with `stubgen:subpath <subpath>` are left out. Test
// skeletons and test-mapping rows belong to the run that includes ".". A
// subpath run renders the package's other public types through the package's
// own --import mapping.
export function generateGoStubs({ sourceRoot, packageKey, outDir, goPackage, repoRoot, dependencyRoots = [], imports = {}, scope = "public", subpaths }) {
  const packageDir = path.join(sourceRoot, "packages", packageKey);
  if (!["public", "module"].includes(scope)) throw new Error(`unknown scope ${scope}; use public or module`);
  const allPublicEntries = packageEntries(packageDir);
  for (const subpath of subpaths ?? []) {
    if (!allPublicEntries.some((entry) => entry.subpath === subpath)) throw new Error(`packages/${packageKey} has no public subpath ${subpath}`);
  }
  const existing = scanGoPackage(outDir);
  const selected = (entry) => (subpaths ? subpaths.includes(entry.subpath) : !existing.delegatedSubpaths.has(entry.subpath));
  const publicEntries = allPublicEntries.filter(selected);
  const generatesTests = !subpaths || subpaths.includes(".");
  const entries = scope === "module" ? [...publicEntries, ...moduleEntries(packageDir)] : publicEntries;
  if (entries.length === 0) throw new Error(`packages/${packageKey} has no public entry points; use --scope module to stub every src/ export`);
  const compilerOptions = {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    allowImportingTsExtensions: true,
    noEmit: true,
    strict: true,
    skipLibCheck: true,
    lib: ["lib.es2023.d.ts", "lib.dom.d.ts"],
    baseUrl: sourceRoot,
    paths: workspacePaths(sourceRoot),
  };
  const selfName = JSON.parse(fs.readFileSync(path.join(packageDir, "package.json"), "utf8")).name;
  const foreignPackages = foreignPackageEntries(sourceRoot, imports)
    .map((foreignPackage) => (foreignPackage.name === selfName ? { ...foreignPackage, entries: subpaths ? foreignPackage.entries.filter((entry) => !selected(entry)) : [] } : foreignPackage))
    .filter((foreignPackage) => foreignPackage.entries.length > 0);
  const program = ts.createProgram([...entries, ...foreignPackages.flatMap((foreignPackage) => foreignPackage.entries)].map((entry) => entry.file), compilerOptions, createHost(compilerOptions, dependencyRoots));
  const checker = program.getTypeChecker();
  const throwing = throwingDeclarations(program, checker, packageDir);
  const packageName = goPackage ?? existing.packageName ?? packageKey.replace(/[^a-z0-9]/gi, "").toLowerCase();
  // A re-export of another workspace package's symbol belongs to that package
  // (rendered through --import or as any), not to this one.
  const exports = collectExports(program, checker, entries).filter((item) => item.declarations[0].getSourceFile().fileName.startsWith(packageDir + path.sep));

  // Assign Go names. Types and values share Go's package namespace; a value
  // that collides with a type of the same upstream name gets a Value suffix.
  const owned = new Map();
  const goNames = new Set();
  const plan = [];
  const sorted = [...exports].sort((a, b) => {
    const fa = a.declarations[0].getSourceFile().fileName;
    const fb = b.declarations[0].getSourceFile().fileName;
    return fa.localeCompare(fb) || a.declarations[0].pos - b.declarations[0].pos;
  });
  // Types claim their Go names first; a value whose name collides with a type
  // becomes New<Name> (a function) or <Name>Value.
  const typeDeclarationOf = (item) => item.declarations.find((d) => ts.isInterfaceDeclaration(d) || ts.isTypeAliasDeclaration(d) || ts.isClassDeclaration(d) || ts.isEnumDeclaration(d));
  const valueDeclarationOf = (item) => item.declarations.find((d) => ts.isFunctionDeclaration(d) || ts.isVariableDeclaration(d));
  for (const item of sorted) {
    const typeDeclaration = typeDeclarationOf(item);
    if (!typeDeclaration) continue;
    let name = goName(item.name);
    while (goNames.has(name)) name = `${name}Type`;
    const kind = ts.isClassDeclaration(typeDeclaration) ? "class" : ts.isEnumDeclaration(typeDeclaration) ? "enum" : "type";
    owned.set(item.symbol, { goName: name, kind, typeParameterCount: typeDeclaration.typeParameters?.length ?? 0 });
    goNames.add(name);
  }
  for (const item of sorted) {
    const typeDeclaration = typeDeclarationOf(item);
    const valueDeclaration = valueDeclarationOf(item);
    if (typeDeclaration) plan.push({ ...item, declaration: typeDeclaration, goName: owned.get(item.symbol).goName, kind: owned.get(item.symbol).kind });
    if (valueDeclaration) {
      const isFunction = ts.isFunctionDeclaration(valueDeclaration);
      let name = goName(item.name);
      if (goNames.has(name)) name = isFunction && !goNames.has(`New${name}`) ? `New${name}` : `${name}Value`;
      while (goNames.has(name)) name = `${name}Value`;
      goNames.add(name);
      if (!typeDeclaration) owned.set(item.symbol, { goName: name, kind: "value", typeParameterCount: 0 });
      plan.push({ ...item, declaration: valueDeclaration, goName: name, kind: isFunction ? "function" : "variable" });
    }
  }

  nilableNames.clear();
  optionalStructNames.clear();
  sealedMemberNames.clear();
  for (const item of plan) {
    if (item.kind !== "type") continue;
    const type = checker.getTypeAtLocation(item.declaration);
    const properties = type.flags & ts.TypeFlags.Object && !type.isUnion() ? type.getProperties() : [];
    if (properties.length > 0 && type.getCallSignatures().length === 0 && properties.every((property) => property.flags & ts.SymbolFlags.Optional)) optionalStructNames.add(item.goName);
  }
  const ownedByType = new Map();
  for (const item of plan) if (item.kind === "type") ownedByType.set(checker.getTypeAtLocation(item.declaration), item.goName);
  for (const item of plan) {
    if (item.kind !== "type" || !ts.isTypeAliasDeclaration(item.declaration)) continue;
    const type = checker.getTypeAtLocation(item.declaration);
    if (!type.isUnion()) continue;
    const present = type.types.filter((member) => !(member.flags & (ts.TypeFlags.Undefined | ts.TypeFlags.Null)));
    if (!present.every((member) => member.flags & ts.TypeFlags.Object)) continue;
    for (const member of present) {
      const name = ownedByType.get(member);
      if (name) sealedMemberNames.add(name);
    }
  }
  for (const item of plan) {
    if (item.kind !== "type") continue;
    const declaration = item.declaration;
    const type = checker.getTypeAtLocation(declaration);
    const methodsOnly = ts.isInterfaceDeclaration(declaration) && declaration.members.length > 0 && declaration.members.every((member) => ts.isMethodSignature(member));
    const sealed = type.isUnion() && type.types.filter((member) => !(member.flags & (ts.TypeFlags.Undefined | ts.TypeFlags.Null))).every((member) => member.flags & ts.TypeFlags.Object);
    if (methodsOnly || (ts.isTypeAliasDeclaration(declaration) && (type.getCallSignatures().length > 0 || sealed))) nilableNames.add(item.goName);
  }

  // Index the interned type of each owned alias and interface so structural
  // references (a TypeBox schema reused in another schema) render by name.
  const typeIndex = new Map();
  for (const item of plan) {
    if (item.kind !== "type") continue;
    const type = checker.getTypeAtLocation(item.declaration);
    const indexable = type.flags & (ts.TypeFlags.Object | ts.TypeFlags.Intersection) || (type.isUnion() && !(type.flags & ts.TypeFlags.Boolean) && !type.types.every((member) => member.flags & (ts.TypeFlags.Undefined | ts.TypeFlags.Null)));
    if (indexable && !typeIndex.has(type) && !(item.declaration.typeParameters?.length)) typeIndex.set(type, owned.get(item.symbol));
  }

  const foreign = indexForeignPackages(program, checker, foreignPackages);

  const constNames = new Map();
  for (const item of plan) {
    if (item.kind === "variable" && item.declaration.parent.flags & ts.NodeFlags.Const) constNames.set(item.name, item.goName);
  }

  const files = new Map(); // go file base → { imports, chunks, upstream }
  const report = { generated: [], skipped: [] };
  const fileFor = (declaration) => {
    const relative = normalizePath(path.relative(packageDir, declaration.getSourceFile().fileName));
    const base = goFileBase(relative);
    if (!files.has(base)) files.set(base, { imports: new Set(), chunks: [], upstream: relative });
    return files.get(base);
  };

  for (const item of plan) {
    const file = fileFor(item.declaration);
    const renderer = new Renderer(checker, owned, file.imports, typeIndex);
    renderer.foreign = foreign;
    const relative = `packages/${packageKey}/${file.upstream}`;
    const label = upstreamLabel(relative, item.declaration, item.name);
    const doc = (lines) => goDoc(item.goName, lines);
    const docText = docLines(item.declaration, item.declaration.getSourceFile(), label);
    const declared = existing.declared.has(item.goName);
    const record = (goSymbol, status) => (status === "generated" ? report.generated : report.skipped).push({ upstream: `${relative}#${item.name}`, go: goSymbol });

    if (item.kind === "class") {
      const declaration = item.declaration;
      const typeParams = typeParameterList(renderer, declaration);
      const use = typeParameterUse(declaration);
      const errorClass = isErrorClass(checker, declaration);
      const chunks = [];
      if (!declared) {
        const fields = [];
        if (errorClass) fields.push("\tMessage string");
        for (const member of declaration.members) {
          if (!ts.isPropertyDeclaration(member) || !isPublicMember(member) || isStatic(member)) continue;
          if (!errorClass) continue;
          const memberName = member.name.getText();
          if (memberName === "name" || memberName === "message") continue;
          fields.push(`\t${goName(memberName)} ${renderer.type(checker.getTypeAtLocation(member))}`);
        }
        chunks.push(`${doc(docText)}\ntype ${item.goName}${typeParams} struct {\n${fields.join("\n")}${fields.length ? "\n" : ""}}`);
        if (errorClass) chunks.push(`func (err *${item.goName}${use}) Error() string { return err.Message }`);
        record(item.goName, "generated");
      } else record(item.goName, "present");
      const canAddMethods = !declared || existing.structs.has(item.goName);
      const ctor = declaration.members.find(ts.isConstructorDeclaration);
      const ctorName = `New${item.goName}`;
      if (!existing.declared.has(ctorName) && !goNames.has(ctorName) && (ctor || !errorClass) && !(errorClass && trivialErrorConstructor(ctor))) {
        const signature = ctor ? checker.getSignatureFromDeclaration(ctor) : undefined;
        const { params } = signature ? renderer.signature(signature, { withContext: false }) : { params: [] };
        const results = [`*${item.goName}${use}`];
        if (ctor && throwing.has(ctor)) results.push("error");
        const line = ctor ? lineOf(ctor) : lineOf(declaration);
        chunks.push(`// ${ctorName} ports the ${item.name} constructor at ${relative}:${line}.\nfunc ${ctorName}${typeParams}(${params.map((p) => `${p.name} ${p.type}`).join(", ")})${formatResults(results)} {\n\tpanic("unported: ${relative}#${item.name}.constructor")\n}`);
        goNames.add(ctorName);
        record(ctorName, "generated");
      }
      if (canAddMethods) {
        const seenMethods = new Set(errorClass ? ["Error"] : []);
        for (const member of declaration.members) {
          if (!isPublicMember(member) || member.name === undefined || ts.isComputedPropertyName(member.name)) continue;
          const memberName = member.name.getText();
          let methodName = goName(memberName);
          if (seenMethods.has(methodName)) continue;
          const statik = isStatic(member);
          if (ts.isMethodDeclaration(member) || ts.isGetAccessorDeclaration(member) || (ts.isPropertyDeclaration(member) && !errorClass && !statik)) {
            if (errorClass) continue;
            if (statik) {
              if (existing.declared.has(methodName)) {
                record(methodName, "present");
                continue;
              }
              methodName = goNames.has(methodName) ? `${item.goName}${methodName}` : methodName;
              if (existing.declared.has(methodName) || goNames.has(methodName)) continue;
              goNames.add(methodName);
            } else if (existing.methods.has(`${item.goName}.${methodName}`) || (!ts.isMethodDeclaration(member) && existing.fields.has(`${item.goName}.${methodName}`))) {
              // A hand-written field ports a property or getter; a method of the same name would not compile.
              record(`${item.goName}.${methodName}`, "present");
              continue;
            }
            seenMethods.add(methodName);
            const symbol = `${relative}#${item.name}.${memberName}`;
            let params = [];
            let results;
            if (ts.isMethodDeclaration(member)) {
              const signature = checker.getSignatureFromDeclaration(member);
              const rendered = renderer.signature(signature, { withContext: true, throws: throwing.has(member) });
              params = rendered.params;
              results = rendered.results;
            } else {
              results = [renderer.type(checker.getTypeAtLocation(member))].filter((r) => r !== "struct{}");
            }
            const receiver = statik ? "" : `(${receiverName(item.goName)} *${item.goName}${use}) `;
            const typeParamsForFunc = statik ? typeParams : "";
            const memberDoc = docLines(member, member.getSourceFile(), `${relative}:${lineOf(member)} (${item.name}.${memberName})`);
            chunks.push(`${goDoc(methodName, memberDoc)}\nfunc ${receiver}${methodName}${typeParamsForFunc}(${params.map((p) => `${p.name} ${p.type}`).join(", ")})${formatResults(results)} {\n\tpanic("unported: ${symbol}")\n}`);
            record(statik ? methodName : `${item.goName}.${methodName}`, "generated");
          }
        }
      }
      if (chunks.length) file.chunks.push(chunks.join("\n\n"));
      continue;
    }

    if (declared) {
      record(item.goName, "present");
      continue;
    }

    if (item.kind === "type" && ts.isInterfaceDeclaration(item.declaration)) {
      file.chunks.push(renderInterface(item, renderer, checker, doc(docText), relative, existing));
      record(item.goName, "generated");
      continue;
    }
    if (item.kind === "type" && ts.isTypeAliasDeclaration(item.declaration)) {
      file.chunks.push(renderAlias(item, renderer, checker, doc(docText), owned));
      record(item.goName, "generated");
      continue;
    }
    if (item.kind === "enum") {
      const members = item.declaration.members.map((member) => {
        const value = checker.getConstantValue(member);
        return `\t${item.goName}${goName(member.name.getText())} ${item.goName} = ${typeof value === "string" ? JSON.stringify(value) : value ?? 0}`;
      });
      const base = item.declaration.members.some((member) => typeof checker.getConstantValue(member) === "string") ? "string" : "float64";
      file.chunks.push(`${doc(docText)}\ntype ${item.goName} ${base}\n\nconst (\n${members.join("\n")}\n)`);
      record(item.goName, "generated");
      continue;
    }
    if (item.kind === "function") {
      const declaration = item.declaration;
      const signature = checker.getSignatureFromDeclaration(declaration);
      const typeParams = typeParameterList(renderer, declaration);
      const { params, results } = renderer.signature(signature, { withContext: true, throws: throwing.has(declaration) });
      file.chunks.push(`${doc(docText)}\nfunc ${item.goName}${typeParams}(${params.map((p) => `${p.name} ${p.type}`).join(", ")})${formatResults(results)} {\n\tpanic("unported: ${relative}#${item.name}")\n}`);
      record(item.goName, "generated");
      continue;
    }
    if (item.kind === "variable") {
      const declaration = item.declaration;
      const isConst = declaration.parent.flags & ts.NodeFlags.Const;
      const initializer = declaration.initializer;
      const constant = isConst ? goConstExpression(initializer, constNames) : undefined;
      if (constant !== undefined) {
        file.chunks.push(`${doc(docText)}\nconst ${item.goName} = ${constant}`);
      } else if (initializer && (ts.isArrowFunction(initializer) || ts.isFunctionExpression(initializer))) {
        const signature = checker.getSignatureFromDeclaration(initializer);
        const { params, results } = renderer.signature(signature, { withContext: true, throws: throwing.has(initializer) });
        file.chunks.push(`${doc(docText)}\nfunc ${item.goName}(${params.map((p) => `${p.name} ${p.type}`).join(", ")})${formatResults(results)} {\n\tpanic("unported: ${relative}#${item.name}")\n}`);
      } else {
        const rendered = renderer.type(checker.getTypeAtLocation(declaration));
        file.chunks.push(`${doc([...docText, "The upstream initializer is unported; the value is Go's zero value."])}\nvar ${item.goName} ${rendered === "struct{}" ? "any" : rendered}`);
      }
      record(item.goName, "generated");
    }
  }

  const outputs = [];
  for (const [base, file] of [...files.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    if (file.chunks.length === 0) continue;
    const text = file.chunks.join("\n\n");
    const aliasOf = (name) => name.split("/").pop().replace(/[^A-Za-z0-9_]/g, "");
    const imports = [...file.imports].filter((name) => new RegExp(`\\b${aliasOf(name)}\\.`).test(text)).sort();
    const importLine = (name) => (aliasOf(name) === name.split("/").pop() ? `\t"${name}"` : `\t${aliasOf(name)} "${name}"`);
    const importBlock = imports.length ? `import (\n${imports.map(importLine).join("\n")}\n)\n\n` : "";
    let body = `\npackage ${packageName}\n\n${importBlock}${file.chunks.join("\n\n")}\n`;
    outputs.push({ name: `${base}_stub.go`, content: withHeader(`packages/${packageKey}/${file.upstream}`, body) });
  }

  const tests = generatesTests ? generateTestSkeletons({ sourceRoot, packageKey, packageName, existing, outDir, repoRoot }) : { outputs: [], rows: [] };
  const all = [...outputs, ...tests.outputs];
  // A generated file whose every declaration is now hand-written is removed.
  const named = new Set(all.map((output) => output.name));
  if (fs.existsSync(outDir)) {
    for (const name of fs.readdirSync(outDir).sort()) {
      if (named.has(name) || !/(_stub\.go|_upstream_test\.go)$/.test(name)) continue;
      const header = readHeader(fs.readFileSync(path.join(outDir, name), "utf8"));
      if (header) all.push({ name, remove: true });
    }
  }
  return { outputs: all, report, rows: tests.rows, packageName };
}

// goDoc starts the comment with the Go name and the upstream site, then
// carries the upstream JSDoc text.
function goDoc(name, lines) {
  const site = lines[lines.length - 1];
  const prose = lines.slice(0, -1);
  return [`// ${name} ${lowerFirst(site)}`, ...(prose.length ? ["//", ...prose.map((line) => `// ${line}`)] : [])].join("\n");
}

function lowerFirst(line) {
  return line.replace(/^[A-Z](?=[a-z])/, (c) => c.toLowerCase());
}

function receiverName(goTypeName) {
  const first = goTypeName.replace(/[^A-Za-z]/g, "")[0]?.toLowerCase() ?? "x";
  return GO_KEYWORDS.has(first) ? `${first}x` : first;
}

function isPublicMember(member) {
  const modifiers = ts.getCombinedModifierFlags(member);
  if (modifiers & (ts.ModifierFlags.Private | ts.ModifierFlags.Protected)) return false;
  if (member.name && ts.isPrivateIdentifier(member.name)) return false;
  return true;
}

function isStatic(member) {
  return Boolean(ts.getCombinedModifierFlags(member) & ts.ModifierFlags.Static);
}

function renderInterface(item, renderer, checker, docText, relative, existing) {
  const declaration = item.declaration;
  renderer.rendering = renderer.owned.get(item.symbol);
  const typeParams = typeParameterList(renderer, declaration);
  const type = checker.getTypeAtLocation(declaration);
  const properties = type.getProperties();
  const methods = [];
  const fields = [];
  for (const property of properties) {
    const member = property.valueDeclaration ?? property.declarations?.[0];
    if (!member || !validField(property.name)) continue;
    if (sealedMemberNames.has(item.goName) && checker.getTypeOfSymbolAtLocation(property, member).flags & ts.TypeFlags.StringLiteral) continue;
    const propertyType = checker.getTypeOfSymbolAtLocation(property, member);
    const optional = Boolean(property.flags & ts.SymbolFlags.Optional);
    if (ts.isMethodSignature(member) || ts.isMethodDeclaration(member)) {
      const signature = checker.getSignatureFromDeclaration(member);
      const { params, results } = renderer.signature(signature, { withContext: true });
      methods.push({ name: goName(property.name), upstream: property.name, signature: `(${params.map((p) => `${p.name} ${p.type}`).join(", ")})${formatResults(results)}` });
    } else {
      let rendered = renderer.type(propertyType);
      if (rendered === "struct{}") rendered = "any";
      fields.push(`\t${goName(property.name)} ${rendered} \`json:"${property.name}${optional ? ",omitempty" : ""}"\``);
    }
  }
  if (fields.length === 0 && methods.length > 0) {
    return `${docText}\ntype ${item.goName}${typeParams} interface {\n${methods.map((method) => `\t${method.name}${method.signature}`).join("\n")}\n}`;
  }
  const chunks = [`${docText}\ntype ${item.goName}${typeParams} struct {\n${fields.join("\n")}${fields.length ? "\n" : ""}}`];
  const use = typeParameterUse(declaration);
  for (const method of methods) {
    if (existing.methods.has(`${item.goName}.${method.name}`)) continue;
    chunks.push(`func (${receiverName(item.goName)} *${item.goName}${use}) ${method.name}${method.signature} {\n\tpanic("unported: ${relative}#${item.name}.${method.upstream}")\n}`);
  }
  return chunks.join("\n\n");
}

function renderAlias(item, renderer, checker, docText, owned) {
  const declaration = item.declaration;
  renderer.rendering = owned.get(item.symbol);
  const typeParams = typeParameterList(renderer, declaration);
  const type = checker.getTypeAtLocation(declaration);
  const present = type.isUnion() ? type.types.filter((member) => !(member.flags & (ts.TypeFlags.Undefined | ts.TypeFlags.Null))) : [type];
  if (isTupleLike(checker, type)) return `${docText}\ntype ${item.goName}${typeParams} = []any`;
  // A closed set of string literals becomes a named string with one constant per value.
  if (type.isUnion() && present.length > 1 && present.every((member) => member.flags & ts.TypeFlags.StringLiteral)) {
    const used = new Set();
    const constants = present.map((member) => {
      const words = member.value.replace(/\[\]/g, " array").replace(/[^A-Za-z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ""));
      let name = `${item.goName}${goName(words || "Empty")}`;
      for (let index = 2; used.has(name); index++) name = `${item.goName}${goName(words || "Empty")}${index}`;
      used.add(name);
      return `\t${name} ${item.goName} = ${JSON.stringify(member.value)}`;
    });
    return `${docText}\ntype ${item.goName} string\n\nconst (\n${constants.join("\n")}\n)`;
  }
  // A union of object shapes becomes a sealed interface; each named member
  // owned by this package implements its marker method.
  const memberOwner = (member) => renderer.typeIndex.get(member) ?? renderer.ownedName(member.aliasSymbol) ?? renderer.ownedName(member.getSymbol());
  // Anonymous object variants that share fields (Pi's record unions) merge
  // into one struct; a field missing from some variant is optional.
  if (type.isUnion() && present.length > 1 && present.every((member) => member.flags & ts.TypeFlags.Object && member.getCallSignatures().length === 0 && !memberOwner(member))) {
    const fields = new Map();
    for (const member of present) {
      for (const property of member.getProperties()) {
        if (!validField(property.name)) continue;
        const declarationNode = property.valueDeclaration ?? property.declarations?.[0];
        const propertyType = declarationNode ? checker.getTypeOfSymbolAtLocation(property, declarationNode) : undefined;
        const rendered = propertyType ? renderer.type(propertyType) : "any";
        const entry = fields.get(property.name) ?? { types: new Set(), count: 0, optional: false };
        entry.types.add(rendered === "struct{}" ? "any" : rendered);
        entry.count += 1;
        entry.optional ||= Boolean(property.flags & ts.SymbolFlags.Optional);
        fields.set(property.name, entry);
      }
    }
    const lines = [...fields.entries()].map(([name, entry]) => {
      const optional = entry.optional || entry.count < present.length;
      let rendered = entry.types.size === 1 ? [...entry.types][0] : "any";
      if (optional && entry.count < present.length) rendered = pointerTo(rendered);
      return `\t${goName(name)} ${rendered} \`json:"${name}${optional ? ",omitempty" : ""}"\``;
    });
    return `${docText}\ntype ${item.goName}${typeParams} struct {\n${lines.join("\n")}\n}`;
  }
  if (type.isUnion() && present.length > 1 && present.every((member) => member.flags & ts.TypeFlags.Object)) {
    const marker = `is${item.goName}`;
    const lines = [`${docText}\ntype ${item.goName}${typeParams} interface {\n\t${marker}()\n}`];
    for (const member of present) {
      const memberOwned = memberOwner(member);
      if (memberOwned && memberOwned.kind === "type" && memberOwned.typeParameterCount === 0 && memberOwned.goName !== item.goName) {
        lines.push(`func (${memberOwned.goName}) ${marker}() {}`);
      }
    }
    return lines.join("\n\n");
  }
  // An object shape (including TypeBox Static<> results) becomes a struct.
  if (!type.isUnion() && type.flags & ts.TypeFlags.Object && type.getCallSignatures().length === 0 && type.getProperties().length > 0 && !checker.isArrayType(type) && !type.aliasTypeArguments?.length && !(type.getSymbol() && renderer.ownedName(type.getSymbol()) && renderer.ownedName(type.getSymbol()).goName !== item.goName)) {
    const discriminant = (property) => {
      if (!sealedMemberNames.has(item.goName)) return false;
      const member = property.valueDeclaration ?? property.declarations?.[0];
      return Boolean(member) && Boolean(checker.getTypeOfSymbolAtLocation(property, member).flags & ts.TypeFlags.StringLiteral);
    };
    const fields = type.getProperties().filter((property) => validField(property.name) && !discriminant(property)).map((property) => {
      const member = property.valueDeclaration ?? property.declarations?.[0];
      const propertyType = member ? checker.getTypeOfSymbolAtLocation(property, member) : checker.getAnyType?.();
      let rendered = propertyType ? renderer.type(propertyType) : "any";
      if (rendered === "struct{}" || rendered.includes(item.goName)) rendered = rendered.includes(`*${item.goName}`) ? rendered : rendered === "struct{}" ? "any" : `*${rendered}`.replace("**", "*");
      const optional = Boolean(property.flags & ts.SymbolFlags.Optional);
      return `\t${goName(property.name)} ${rendered} \`json:"${property.name}${optional ? ",omitempty" : ""}"\``;
    });
    return `${docText}\ntype ${item.goName}${typeParams} struct {\n${fields.join("\n")}\n}`;
  }
  const signatures = type.getCallSignatures();
  if (signatures.length > 0 && type.getProperties().length === 0) {
    return `${docText}\ntype ${item.goName}${typeParams} ${renderer.funcType(signatures[0], 0)}`;
  }
  // Anything else aliases its rendered Go type; self-references fall back to any.
  const self = owned.get(item.symbol);
  owned.delete(item.symbol);
  let rendered = renderer.type(type);
  owned.set(item.symbol, self);
  // Go cannot alias a bare type parameter (`type MaybePromise[T any] = T`).
  if (rendered === "struct{}" || renderer.typeParams.has(rendered)) rendered = "any";
  return `${docText}\ntype ${item.goName}${typeParams} = ${rendered}`;
}

// ── Tests ───────────────────────────────────────────────────────────────────

function testFilesOf(packageDir) {
  const out = [];
  const visit = (dir) => {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      if (entry.name === "node_modules" || entry.name === "dist") continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) visit(full);
      else if (entry.name.endsWith(".test.ts")) out.push(full);
    }
  };
  visit(path.join(packageDir, "test"));
  return out;
}

// testCases mirrors extract-test-inventory.mjs: describe paths join with " › ".
function testCases(file, text) {
  const source = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const cases = [];
  const dynamic = [];
  const chainOf = (call) => {
    let expression = call.expression;
    for (;;) {
      if (ts.isPropertyAccessExpression(expression)) expression = expression.expression;
      else if (ts.isCallExpression(expression)) expression = expression.expression;
      else break;
    }
    return ts.isIdentifier(expression) ? expression.text : undefined;
  };
  const visit = (node, stack) => {
    if (ts.isCallExpression(node)) {
      const base = chainOf(node);
      if (base === "describe" || base === "it" || base === "test") {
        const arg = node.arguments[0];
        const literal = arg && (ts.isStringLiteral(arg) || ts.isNoSubstitutionTemplateLiteral(arg) || ts.isTemplateExpression(arg));
        if (literal) {
          const title = ts.isStringLiteral(arg) || ts.isNoSubstitutionTemplateLiteral(arg) ? arg.text : arg.getText(source).replace(/^[`'"]|[`'"]$/g, "");
          if (base === "describe") {
            ts.forEachChild(node, (child) => visit(child, [...stack, title]));
            return;
          }
          cases.push({ id: [...stack, title].join(" \u203a "), line: lineOf(node) });
        } else if (base !== "describe" && node.arguments[1] && (ts.isArrowFunction(node.arguments[1]) || ts.isFunctionExpression(node.arguments[1]))) {
          dynamic.push({ line: lineOf(node), id: [...stack, `<computed: ${arg?.getText(source) ?? ""}>`].join(" \u203a ") });
        }
      }
    }
    ts.forEachChild(node, (child) => visit(child, stack));
  };
  visit(source, []);
  return [...cases, ...dynamic].sort((a, b) => a.line - b.line);
}

function testFunctionName(relative) {
  const base = relative.replace(/^test\//, "").replace(/\.test\.ts$/, "");
  const words = base.split(/[^A-Za-z0-9]+/).filter(Boolean);
  // cbor/cbor → Cbor: drop a directory that repeats the file name.
  const unique = words.filter((word, index) => index === 0 || word.toLowerCase() !== words[index - 1].toLowerCase());
  return `Test${unique.map((word) => word[0].toUpperCase() + word.slice(1)).join("")}Upstream`;
}

function generateTestSkeletons({ sourceRoot, packageKey, packageName, existing, outDir, repoRoot }) {
  const packageDir = path.join(sourceRoot, "packages", packageKey);
  const relativeDir = normalizePath(path.relative(repoRoot ?? process.cwd(), outDir));
  const ported = portedCases(existing.testFiles, relativeDir);
  const outputs = [];
  const rows = [];
  for (const file of testFilesOf(packageDir)) {
    const text = fs.readFileSync(file, "utf8");
    const relative = normalizePath(path.relative(packageDir, file));
    const upstreamPath = `packages/${packageKey}/${relative}`;
    const cases = testCases(file, text);
    const missing = cases.filter((testCase) => !ported.has(`${upstreamPath}:${testCase.line}`));
    const evidence = new Set();
    for (const testCase of cases) for (const reference of ported.get(`${upstreamPath}:${testCase.line}`) ?? []) evidence.add(reference);
    const goFile = `${relative.replace(/^test\//, "").replace(/\.test\.ts$/, "").replace(/[/.-]/g, "_").toLowerCase()}_upstream_test.go`;
    const functionName = testFunctionName(relative);
    if (missing.length > 0) {
      const subtests = missing.map((testCase) => `\tt.Run(${JSON.stringify(testCase.id)}, func(t *testing.T) {\n\t\t// upstream: ${upstreamPath}:${testCase.line}\n\t\tt.Skip("unported")\n\t})`);
      const body = `\npackage ${packageName}\n\nimport "testing"\n\n// ${functionName} ports ${upstreamPath}. Each subtest names one upstream case.\nfunc ${functionName}(t *testing.T) {\n${subtests.join("\n")}\n}\n`;
      // A porter who claims a skeleton (drops its header) owns it; its
      // remaining t.Skip("unported") cases stay visible there.
      outputs.push({ name: goFile, content: withHeader(upstreamPath, body), yieldToHand: true });
    } else {
      outputs.push({ name: goFile, remove: true });
    }
    const row = { path: upstreamPath, upstreamTestHash: `sha256:${sha256(text)}`, caseCount: cases.length, missing: missing.map((testCase) => `${testCase.line} ${testCase.id}`) };
    if (missing.length === 0) row.disposition = "ported";
    else if (missing.length < cases.length) row.disposition = "partial";
    else row.disposition = "pending";
    row.evidence = [...evidence].sort();
    rows.push(row);
  }
  return { outputs, rows };
}

// writeOutputs applies the generator's ownership rule: write a file only when
// it is absent or carries an intact generator header, and refuse otherwise.
export function writeOutputs(outDir, outputs, { check = false } = {}) {
  const conflicts = [];
  const changes = [];
  for (const output of outputs) {
    const target = path.join(outDir, output.name);
    const exists = fs.existsSync(target);
    const current = exists ? fs.readFileSync(target, "utf8") : undefined;
    if (exists) {
      const header = readHeader(current);
      if ((output.remove || output.yieldToHand) && !header) continue; // hand-written test file: its markers were already read.
      if (!header) {
        conflicts.push(`${target}: hand-written file; the generator never overwrites it`);
        continue;
      }
      if (!header.valid) {
        conflicts.push(`${target}: generated file was edited (hash mismatch); move the edits into a hand-written file or delete it`);
        continue;
      }
    }
    if (output.remove) {
      if (exists) changes.push({ target, action: "remove" });
      continue;
    }
    if (current === output.content) continue;
    changes.push({ target, action: exists ? "update" : "create", content: output.content });
  }
  if (conflicts.length) return { conflicts, changes: [] };
  if (!check) {
    fs.mkdirSync(outDir, { recursive: true });
    for (const change of changes) {
      if (change.action === "remove") fs.rmSync(change.target);
      else fs.writeFileSync(change.target, change.content);
    }
  }
  return { conflicts, changes };
}

// applyTestMapping updates the reviewed ledger rows of this package's test
// files in place. It rewrites only those entries' text, so every other row
// keeps its exact bytes (the ledger mixes escaped and raw characters). A
// reviewed designed-out or divergence row changes only when every case is
// cited: citations cannot show that its reason no longer holds, and a pending
// or partial rewrite would drop that reason.
const REVIEWED_EXCLUSIONS = new Set(["designed-out", "divergence"]);

export function applyTestMapping(ledgerPath, rows, { rationale } = {}) {
  let text = fs.readFileSync(ledgerPath, "utf8");
  const ledger = JSON.parse(text);
  const indent = /\n( +|\t)"/.exec(text)?.[1] ?? "  ";
  let changed = 0;
  for (const row of rows) {
    const previous = ledger.entries.find((entry) => entry.path === row.path);
    const next = { path: row.path, disposition: row.disposition, upstreamTestHash: row.upstreamTestHash };
    if (row.evidence.length) next.evidence = row.evidence;
    if (row.disposition === "ported") next.rationale = rationale?.(row) ?? `All ${row.caseCount} upstream cases are ported; each Go case cites its upstream line.`;
    else if (row.disposition === "partial") next.rationale = `Unported cases: ${row.missing.join("; ")}.`;
    if (previous) {
      if (REVIEWED_EXCLUSIONS.has(previous.disposition) && row.disposition !== "ported") continue;
      // Keep a reviewed ported row whose evidence and hash are unchanged.
      if (row.disposition === "ported" && previous.disposition === "ported" && previous.rationale && JSON.stringify(previous.evidence) === JSON.stringify(next.evidence) && previous.upstreamTestHash === next.upstreamTestHash) continue;
      if (JSON.stringify(previous) === JSON.stringify(next)) continue;
    }
    text = replaceEntry(text, row.path, next, indent);
    changed += 1;
  }
  JSON.parse(text);
  fs.writeFileSync(ledgerPath, text);
  return changed;
}

// replaceEntry swaps the entry object whose "path" is entryPath, or inserts it
// before the first entry with a greater path.
function replaceEntry(text, entryPath, entry, indent) {
  const objects = entryObjects(text);
  const render = (base) => JSON.stringify(entry, null, indent).split("\n").map((line, index) => (index === 0 ? line : base + line)).join("\n");
  const found = objects.find((object) => object.path === entryPath);
  if (found) return text.slice(0, found.start) + render(found.base) + text.slice(found.end);
  const after = objects.find((object) => object.path > entryPath);
  if (after) return `${text.slice(0, after.start)}${render(after.base)},\n${after.base}${text.slice(after.start)}`;
  const last = objects[objects.length - 1];
  return `${text.slice(0, last.end)},\n${last.base}${render(last.base)}${text.slice(last.end)}`;
}

// entryObjects scans the top-level "entries" array for its objects' spans.
function entryObjects(text) {
  const begin = text.indexOf("[", text.indexOf('"entries"'));
  const out = [];
  let depth = 0;
  let inString = false;
  let start = -1;
  for (let index = begin + 1; index < text.length; index++) {
    const char = text[index];
    if (inString) {
      if (char === "\\") index++;
      else if (char === '"') inString = false;
      continue;
    }
    if (char === '"') inString = true;
    else if (char === "{") {
      if (depth === 0) start = index;
      depth++;
    } else if (char === "}") {
      depth--;
      if (depth === 0) {
        const lineStart = text.lastIndexOf("\n", start) + 1;
        out.push({ start, end: index + 1, base: text.slice(lineStart, start), path: JSON.parse(text.slice(start, index + 1)).path });
      }
    } else if (char === "]" && depth === 0) break;
  }
  return out;
}
